### ISSUE TITLE
Template link not working with MQTT (HA integration)

### ISSUE THREAD

**Issue by SNoof85** [fmartinou/whats-up-docker#110]
* What I have configured : 
`- wud.link.template=https://github.com/AdguardTeam/AdGuardHome/releases/tag/$${raw}`

* What I have in wud frontend 👍 
![image](https://user-images.githubusercontent.com/25659602/156837964-caef9156-4439-441d-a5bf-5f158e28cefb.png)

* What I have in HA 👎 
![image](https://user-images.githubusercontent.com/25659602/156838017-a21226e8-5fa4-44d6-89c0-d9d11a7c1d4d.png)

The variable ${raw} is not expanded in MQTT trigger.

**Comment by fmartinou** [comment]
Hi,

`Link template` is the value of the template you configured on the container.


The attributes you have to look for are:
- `Link`: contains the expanded value of the template for the current container
- `Result link`: contains the expanded value of the template for the available update

**Comment by fmartinou** [comment]
![IMG_20220304_223524.jpg](https://user-images.githubusercontent.com/16061231/156844956-93141180-3427-43ae-88f1-14159525f996.jpg)

**Comment by SNoof85** [comment]
Am I blind ? I guess no, but on this one I was ! Sorry
