### ISSUE TITLE
Running WUD on local HTTPS using self signed certificate

### ISSUE THREAD

**Issue by ranrinc** [fmartinou/whats-up-docker#111]
Is it possible to run WUD on IP:80 and redirect to IP:443 with self signed certificate?

**Comment by fmartinou** [comment]
Hi,

WUD listens on the port `3000` by default but it can listen on any other port if [`WUD_API_PORT=XYZ`](https://fmartinou.github.io/whats-up-docker/#/api/?id=variables) is defined.

However, WUD is only able to handle HTTP trafic.
It doesn't implement HTTPS with TLS so this part has to be handled by any Reverse Proxy in front of it (HA-Proxy, Traefik, Nginx, Apache...).

What is your exact use-case / setup?

**Comment by ranrinc** [comment]
> Hi,
> 
> WUD listens on the port `3000` by default but it can listen on any other port if [`WUD_API_PORT=XYZ`](https://fmartinou.github.io/whats-up-docker/#/api/?id=variables) is defined.
> 
> However, WUD is only able to handle HTTP trafic. It doesn't implement HTTPS with TLS so this part has to be handled by any Reverse Proxy in front of it (HA-Proxy, Traefik, Nginx, Apache...).
> 
> What is your exact use-case / setup?

Recently just add self signed certificate to all my docker that can be HTTPS so it look better and since WUD already used the certificated anyway (also for remote portainer) wondering if it can HTTPS it self.

**Comment by fmartinou** [comment]
I understand.

Adding the support of HTTPS is pretty easy; I add it to my todo list.

**Comment by fmartinou** [comment]
Hi,

It's implemented in `5.16.0`.
See the [related documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/server/).

Thank you for your feedback!

**Comment by ranrinc** [comment]
> related documentation here

you are the best...

**Comment by ranrinc** [comment]
> Hi,
> 
> It's implemented in `5.16.0`. See the [related documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/server/).
> 
> Thank you for your feedback!

Just upgrade and found that after 5.16.0 is up and running somehow my password did not work and I keep on failing to login. I downgrade it back to 5.15.0 and its back working. Any idea?

**Comment by fmartinou** [comment]
> Just upgrade and found that after 5.16.0 is up and running somehow my password did not work and I keep on failing to login. I downgrade it back to 5.15.0 and its back working. Any idea?

It's fixed in `5.16.1` (details in #112)
