### ISSUE TITLE
Unable to login on 5.16.0

### ISSUE THREAD

**Issue by ranrinc** [fmartinou/whats-up-docker#112]
Unable to login after upgrade to 5.16.0 and its tested when I downgrade to the previous version. Any idea?

**Comment by fmartinou** [comment]
Did you upgrade without changing any configuration or did you upgrade along with enabling new features (TLS support for example) ?

**Comment by fmartinou** [comment]
Which kind of auth are you using (Basic or OIDC)?

**Comment by ranrinc** [comment]
> Did you upgrade without changing any configuration or did you upgrade along with enabling new features (TLS support for example) ?

upgrade without adding TLS does not working, but then commented it out and still not working. Its only working after I downgrade to 5.15.0.

I used basic

**Comment by fmartinou** [comment]
Can you see any errors in your logs by chance?

**Comment by ranrinc** [comment]
> Can you see any errors in your logs by chance?

No error on portainer logs

**Comment by fmartinou** [comment]
I found the bug; probably a side-effect of the upgrade of the webpack bundler 🤔 .
Anyway; a fix is on the go.

Thanks for being such a nice beta-tester 😄 !

**Comment by fmartinou** [comment]
`5.16.1` is out; may you confirm that it solves the issue?

**Comment by ranrinc** [comment]
> `5.16.1` is out; may you confirm that it solves the issue?

thank you its fixed + https is now working perfectly. Earlier forget to replace port 80 with 443 which create an error.. hahahahahaha.

Again thanks...
