### ISSUE TITLE
Docker prune not working?

### ISSUE THREAD

**Issue by arkharim** [fmartinou/whats-up-docker#114]
Hi,

Thanks for this amazing project. 

I open this ticket but I'm unsure my configuration is wrong. I'm using docker compose file but I only use docker trigger, not docker-compose, because I prefer that WUD don't modify the docker compose file. On the other hand, I'm new in Docker and I don't fully understand how it works so may I assuming something not correct.

**Current behavior:**
WUD trigger docker prune don't remove old image during the updating.

From the documentation, I think that that if I set =true the WUD_TRIGGER_DOCKER_{trigger_name}_PRUNE, my old image will be removed.
![image](https://user-images.githubusercontent.com/72758421/158016040-b5049cf1-34ee-453d-8142-cfc3a151cb53.png)

**Expected behavior:** 
Delete old image during the update process.  

**Docker compose file**
![image](https://user-images.githubusercontent.com/72758421/158015587-b74114d5-b331-44e6-87bf-26ed32042a88.png)

**Docker images**
Example of docker images that don't remove correctly.
![image](https://user-images.githubusercontent.com/72758421/158015963-4a33e80c-f45e-473e-879a-2e02915f2a2f.png)

**Logs**
Example of updating: swag and Jellyfin
![image](https://user-images.githubusercontent.com/72758421/158015973-2c0e713e-f53d-4604-9f3c-908b587152cf.png)

**Other information**
Raspbian 32bit

Thanks in advance

**Comment by fmartinou** [comment]
Hi,

Thank you for your support! 👍 

>  I think that that if I set =true the WUD_TRIGGER_DOCKER_{trigger_name}_PRUNE, my old image will be removed.

Your understanding is right; it's the intended behavior.

From the informations you provided, I guess that the `prune` is not working for **non semver tags** (for example `latest`).
I think that `wud` is trying to remove the image `jellyfin:latest` which can not occur because the tag is sill in use (by the newly created container).

The expected behavior would be that `wud` removes the old image using its `sha256` id.

I flag your issue as a bug, try to reproduce on my end and let you know when a fix is available.

**Comment by fmartinou** [comment]
Hi @arkharim ,

Can you give a try to the version `fmartinou/whats-up-docker:fix__114` and let me know if it resolves your issue?

If so, I'll release an official fixed version.
Thank you for your feedback!

**Comment by arkharim** [comment]
Thanks @fmartinou, I'm trying the version. Almost every day I have a new image, so I hope I can send feedback soon.

One point, during first start, didn't remove old images, it's ok?

**Comment by fmartinou** [comment]
> One point, during first start, didn't remove old images, it's ok?

Yes, it is.
The removal process is executed when the update event is triggered so it won't remove the previous images because the update event has been processed by the previous buggy `wud` version.

**Comment by arkharim** [comment]
Hi @fmartinou, I can confirm that now it's working correctly. Some images were updated and the old ones deleted.

Thanks for all your support and this nice program.

**Comment by fmartinou** [comment]
Thank you for your feedback 👍.

I'll release a new version including the asap.

**Comment by fmartinou** [comment]
Release `5.16.2` is out.
