### ISSUE TITLE
Disable MQTT updates when rate-limiting

### ISSUE THREAD

**Issue by Caros2017** [fmartinou/whats-up-docker#116]
Sometimes I get an API request limit on dockerhub, which could be plausible. But if this occurs then in the web interface of WUD I can still see which docker container has an update available, but in Home Assistant -through MQTT- I get one of these:
- I get the status unavailable after a reboot of HA
- I get the status up-to-date when I manually trigger the rate limit. Even though there is an update available for that particular container

In the item in HA I see: 
Error message
429 - {"errors":[{"code":"TOOMANYREQUESTS","message":"You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}]} 

Suggestion: Is it possible to not update through MQTT if the rate-limit has been hit?

**Comment by fmartinou** [comment]
Hi @Caros2017 

You are likely describing multiple issues at once 😁 

------------------

> I get the status unavailable after a reboot of HA
[Maybe is your issue this one?](https://github.com/fmartinou/whats-up-docker/issues/113)

------------------

> I get the status up-to-date when I manually trigger the rate limit. Even though there is an update available for that particular container

Which state are you expecting when an error occured? `Up-to-date` or `Update available`?

------------------

> Suggestion: Is it possible to not update through MQTT if the rate-limit has been hit?

HA is a specific usecase; for most use-cases it's important to get the information when an error occurred.

What if the MQTT message would contain both the last "ok" state AND the last "error"?
So in HA you can access all data and can use them the way you want?

**Comment by Caros2017** [comment]
@fmartinou I am so sorry for the late response.
It seems that one of my main problem was an issue with DNS. That's the reason why the states sometimes didn't update. Somehow on the background this was stated as rate limited, but actually this wasn't the case. Took me a while to figure this out.

I haven't had any problems since I have solved this. But still, if someone is experiencing networking issues I assume it's cleaner to add a state like you described.

**Comment by fmartinou** [comment]
I'm glad to see that you've sorted it out 😃 .
I close the issue.
