### ISSUE TITLE
Home Assistant Entities not created

### ISSUE THREAD

**Issue by jsbrich** [fmartinou/whats-up-docker#119]
I used the Home Assistant configuration example from the page, and it seems to connect fine, but only an entity for the wud container is being created.

Here are my configuration flags:
-e WUD_TRIGGER_MQTT_MOSQUITTO_URL="mqtt://mosquitto.jnetinc.local:1883" 
-e WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED="true" 
-e WUD_TRIGGER_MQTT_MOSQUITTO_USER="wud_user" 
-e WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD='password'

If I look at the MQTT broker, I see a wud/container/local/ topic and that shows each of the containers and their status, but in the homeassistant/binary_sensor/, only wud_container_local_wud is listed

**Comment by purplefis** [comment]
Are you persisting data? If you delete the wud.json file in config, and restart WUD they populate instantly

**Comment by adorobis** [comment]
I have the same problem. Removing the wud.json file does not help. In MQTT broker I can see that the binary_sensor topics are properly updated but the corresponding autodiscovery topics are empty, see the image:
![image](https://user-images.githubusercontent.com/19752098/207843849-84107d66-2681-4401-8238-378719c66d0f.png)

**Comment by fmartinou** [comment]
Hi,

The best is probably to perform a full cleanup before running the 6.0.0 version to avoid any side effects.
You can try to follow [the steps I've described there](https://github.com/fmartinou/whats-up-docker/issues/188#issuecomment-1344152367).

**Comment by adorobis** [comment]
OK, I've read another issue and removed MQTT retained topics. binary_sensors are removed from HA now.
The other issue is that for containers that use `latest` tag the update entities don't show available updates...
https://github.com/fmartinou/whats-up-docker/issues/191
