### ISSUE TITLE
Add option to enable CORS for API

### ISSUE THREAD

**Issue by royto** [fmartinou/whats-up-docker#124]
I'm using [homer](https://github.com/bastienwirtz/homer)  as homepage. It supports [custom services](https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md) which allows to add dynamic info to the tile.

For this, the homepageis calling APIs but I'm facing CORS issue that's why i would like to have the option to enable [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

It could be good to be able to specify allowed domain, allowed methods

**Comment by fmartinou** [comment]
Hi @royto ,

Following the documentation on Homer, they mention in their [troubleshooting](https://github.com/bastienwirtz/homer/blob/main/docs/troubleshooting.md) section how to deal with CORS issues.

In summary, 3 solutions:
1. Host all your services on the same domain
2. Configure CORS on the target server (your current Github request btw)
3. Add a CORS proxy server in the middle

Adding CORS to WUD is technically possible & quite easy but I need to understand why it's necessary.

My question is; why can't you serve Homer & all your other services under the same domain? 🤔 
Using a simple RP like Traefik or Nginx in front of them is very common and will resolve your CORS issues, isn't it?

**Comment by royto** [comment]
Hi @fmartinou, 

I've already set a domain on my local network to access my home automation system which is hosted on another machine, not on my NAS where I have all other containers running. I need to rework all this but I'm not a network guy and it could take me some time to put all in place.

The second reason is that I'm implementing an integration for WUD in homer, i'm developing it on my local machine and for testing purpose it is easier to allow CORS (again I'm not a network guy and maybe there is easiest solution) ...

**Comment by fmartinou** [comment]
>  I'm developing it on my local machine and for testing purpose it is easier to allow CORS

That makes sense 😄 .

OK, I'll add an option to allow CORS requests (but I'll log a warning at startup because it can be a vulnerability if badly configured).

**Comment by fmartinou** [comment]
Hi,

I pushed a version adding CORS support `fmartinou/whats-up-docker:feature__124`.

To configure
```yaml
version: '3'

services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    environment:
      - WUD_SERVER_CORS_ENABLED=true
```

To get all supported options, please [take a look at the documentation (draft)](https://github.com/fmartinou/whats-up-docker/tree/feature/%23124/docs/configuration/server).

Can you give it a try?

If it's ok for you, then I'll release a new version with this enhancement.
Thank you!

**Comment by royto** [comment]
Hello @fmartinou, just tested and works as expected.  

There is an error in the documentation, default value for `WUD_SERVER_CORS_ORIGIN` should be * I guess. Here it is the default value for `WUD_SERVER_CORS_METHOD` which need to be updated too 


default value for

**Comment by fmartinou** [comment]
Thank you for your feedback 👍 

I don't see where the doc is wrong? 🤔 

The default values mentioned in the doc are:
- WUD_SERVER_CORS_ORIGIN=*
- WUD_SERVER_CORS_METHODS=GET,HEAD,PUT,PATCH,POST,DELETE

It's true, isn't it?

**Comment by royto** [comment]
not [here](https://github.com/fmartinou/whats-up-docker/tree/feature/%23124/docs/configuration/server)

![image](https://user-images.githubusercontent.com/6990995/164422510-16757720-e641-4c7e-aba9-f49da6a7027d.png)


I've put the corrected version

**Comment by fmartinou** [comment]
My bad, I can see now 😂 
=> I'm gonna fix it

**Comment by fmartinou** [comment]
The feature has been merged into `master`; it will be available in the next release.

**Comment by fmartinou** [comment]
The version `5.17.0` has just been released.
