### ISSUE TITLE
5.16.2, 5.16.1, 5.16.0, 5.15.0, 5.14.1 all crash on startup

### ISSUE THREAD

**Issue by vertex-github** [fmartinou/whats-up-docker#127]
Raspberry Pi 4+:

`docker logs wud`:

```
#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbedfa5cc


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbeea75fc
Trace/breakpoint trap (core dumped)
Trace/breakpoint trap (core dumped)
```

**Comment by fmartinou** [comment]
Hi,

You're listing versions in error from `5.14.1`; does that mean that you've found older versions working on a Pi4+?
(if so, I'm interested to know about them because I'll be able to find the dependency change culprit & to fix it)

**Comment by vertex-github** [comment]
No, I stopped trying at 5.14.1.

I did try and access the container - just running 'node' on it's own
crashes. I get a core file generated inside the container but beyond that i
don't know what to look for next.

**Comment by fmartinou** [comment]
> I did try and access the container - just running 'node' on it's own
crashes.

That's very interesting!

Because that means that it's not an issue with the app itself but rather with the node virtual machine on your arch.

=> I'm gonna do some research to see if there are known compatibility issues caused by the combination of the node.js version, the Alpine OS version and the pi4+ arch.

**Comment by fmartinou** [comment]
I'm using this base image `node:16-alpine`; could you test it (just run node -v or something like that) and confirm that the core dump also occurs?

**Comment by fmartinou** [comment]
I build WUD images for the following arm arch:
- linux/arm/v6
- linux/arm/v7
- linux/arm64

I'm wondering if your pi4+ wouldn't be a linux/arm/v8 ? 🤔

**Comment by vertex-github** [comment]
Running from a 'sh' inside the container:

***@***.***:~ $ docker run -it node:16-alpine sh
/ # node -v
v16.14.2
/ # node


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbe82a64c
Trace/breakpoint trap (core dumped)
/ #

**Comment by vertex-github** [comment]
Running from a 'sh' inside the container:

```
***@***.***:~ $ docker run -it node:16-alpine sh
/ # node -v
v16.14.2
/ # node


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbe82a64c
Trace/breakpoint trap (core dumped)
/ #
```

**Comment by vertex-github** [comment]
> I build WUD images for the following arm arch:
> 
>     * linux/arm/v6
> 
>     * linux/arm/v7
> 
>     * linux/arm64
> 
> 
> I'm wondering if your pi4+ wouldn't be a linux/arm64/v8 ? 🤔

```
**@**:~ $ uname -a
Linux automation 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
```

**Comment by vertex-github** [comment]
Found something - this works:

```
**@*****:~ $ docker run -it --privileged node:16-alpine node
Welcome to Node.js v16.14.2.
Type ".help" for more information.
> 
```

**Comment by fmartinou** [comment]
Instead of full privilege, does this single option work as well?
`--security-opt seccomp=unconfined`

**Comment by fmartinou** [comment]
And with these privileged or security options, does `wud` work as well?

**Comment by fmartinou** [comment]
I suppose that the image `node:17-alpine` is also crashing?

**Comment by vertex-github** [comment]
Yes:


Status: Downloaded newer image for node:17-alpine


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbe93c6a4

**Comment by vertex-github** [comment]
> Instead of full privilege, does this single option work as well? `--security-opt seccomp=unconfined`

Works fine.

**Comment by fmartinou** [comment]
Looks good (except for listening the docker socket).

Did you mount the docker socket into the container?

`-v "/var/run/docker.sock:/var/run/docker.sock"`

**Comment by vertex-github** [comment]
Yep - all done.  Unrelated, I had similar issues with another container and Node 16 (which I just hit):
https://www.zigbee2mqtt.io/guide/installation/02_docker.html#notes-for-raspberry-pi-users

**Comment by fmartinou** [comment]
So, if you install `libseccomp2` as mentioned in the documentation of zigbee2mqtt, does it (wud) work?

**Comment by PascalBu** [comment]
Came here to say that following works on RPI4B:

docker run -d --name Whats-up-Docker \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  -p 3000:3000 \
  --security-opt seccomp=unconfined \
  fmartinou/whats-up-docker

**Comment by fmartinou** [comment]
Thank you for your feedback; I'll update the documentation to mention it for RPI users 👍

**Comment by fmartinou** [comment]
The documentation has been updated.
https://fmartinou.github.io/whats-up-docker/#/faq/?id=core-dumped-on-raspberry-pi

**Comment by vertex-github** [comment]
***@***.***:~/IOTstack $ docker run -it --security-opt seccomp=unconfined
fmartinou/whats-up-docker
Unable to find image 'fmartinou/whats-up-docker:latest' locally
latest: Pulling from fmartinou/whats-up-docker
Digest:
sha256:e81ce578c54b606300f060ea268275350068c04bd02f8c743621571e65c007dd
Status: Downloaded newer image for fmartinou/whats-up-docker:latest
17:46:19.156  INFO whats-up-docker: What's up Docker? is starting (version
= latest)
17:46:19.160  INFO whats-up-docker/store: Load store from (/store/wud.json)
17:46:19.165  INFO whats-up-docker/store: Create Collection app
17:46:19.169  INFO whats-up-docker/store: Migrate data from version
undefined to version latest
17:46:19.172  INFO whats-up-docker/store: Create Collection containers
17:46:19.172  INFO whats-up-docker/prometheus: Init Prometheus module
17:46:19.756  INFO whats-up-docker/registry.ghcr: Register with
configuration {}
17:46:19.765  INFO whats-up-docker/registry.hub: Register with
configuration {}
17:46:19.768  INFO whats-up-docker/registry.lscr: Register with
configuration {}
17:46:19.774  INFO whats-up-docker/registry.quay: Register with
configuration {}
17:46:19.775  INFO whats-up-docker/registry: No Watcher configured => Init
a default one (Docker with default options)
17:46:21.334  INFO whats-up-docker/watcher.docker.local: Register with
configuration {"socket":"/var/run/docker.sock","port":2375,"cron":"0 * * *
*","watchbydefault":true,"watchall":false,"watchevents":true}
17:46:21.337  INFO whats-up-docker/watcher.docker.local: Cron scheduled (0
* * * *)
17:46:21.405  INFO whats-up-docker/registry: No authentication configured
=> Allow anonymous access
17:46:21.419  INFO whats-up-docker/authentication.anonymous.anonymous:
Register with configuration {}
17:46:21.437  WARN whats-up-docker: Anonymous authentication is enabled;
please make sure that the app is not exposed to unsecure networks
17:46:21.458  INFO whats-up-docker/api: Server listening on port 3000 (HTTP)
17:46:22.408  INFO whats-up-docker/watcher.docker.local: Cron started (0 *
* * *)
17:46:22.462  INFO whats-up-docker/watcher.docker.local: Listening to
docker events
17:46:22.486  WARN whats-up-docker/watcher.docker.local: Error when trying
to get the list of the containers to watch (connect ENOENT
/var/run/docker.sock)
17:46:22.486  INFO whats-up-docker/watcher.docker.local: Cron finished (0
containers watched, 0 errors, 0 available updates)
17:46:22.488  WARN whats-up-docker/watcher.docker.local: Unable to listen
to Docker events [connect ENOENT /var/run/docker.sock]

**Comment by fmartinou** [comment]
`17:46:22.488  WARN whats-up-docker/watcher.docker.local: Unable to listen
to Docker events [connect ENOENT /var/run/docker.sock]`

=> have you mounted the Docker socket?
(`-v "/var/run/docker.sock:/var/run/docker.sock"`)

**Comment by vertex-github** [comment]
docker run -it node:16-alpine bash
Unable to find image 'node:16-alpine' locally
16-alpine: Pulling from library/node
57fb4b5f1a47: Pull complete
d1393c274244: Pull complete
1af5ea6e06a0: Pull complete
ccde71dd47a8: Pull complete
Digest:
sha256:28bed508446db2ee028d08e76fb47b935defa26a84986ca050d2596ea67fd506
Status: Downloaded newer image for node:16-alpine


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbea9b64c
