### ISSUE TITLE
Prerelease semvir in link templatea

### ISSUE THREAD

**Issue by whatdaybob** [fmartinou/whats-up-docker#134]
A few repost have the prerelease as a part of the link. Tried raw and unfortunately it has the hash in it. Can we please have prerelease added to the link template. If possible, maybe also the triggers for docker and docker-compose?

Example:

`https://github.com/someowner/somerepo/releases/tag/v${major}.${minor}.${patch}.${prerelease}`

comes back as

`https://github.com/someowner/somerepo/releases/tag/v1.2.3.${prerelease}`

tried both `${prerelease}` and `${pre-release}` and unfortunately `${raw}` has a hash in it.

Did this on mobile app so apologies if there is any formatting issues.

**Comment by fmartinou** [comment]
Hi,

It's implemented in version `5.18.0`.
The supported placeholders in link templates are now `major`, `minor`, `path`, `prerelease`
