### ISSUE TITLE
Documentation error - WUD_TRIGGER_type_name_MODE

### ISSUE THREAD

**Issue by derekoharrow** [fmartinou/whats-up-docker#136]
The docs at https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/ says that WUD_TRIGGER_type_name_MODE can be either simple or batch.

Simple doesn't work and results in an error - it should be single or batch instead.

Or, perhaps, add simple as a valid value too as that would then align with SIMPLEBODY and SIMPLETITLE.

**Comment by fmartinou** [comment]
Hi,
You're absolutely right; something is misaligned 🤔 .

I'll probably opt for renaming `single` to `simple` to align with `SIMPLEBODY` and `SIMPLETITLE` as you've mentioned.
