### ISSUE TITLE
HTTP trigger variables ignored?

### ISSUE THREAD

**Issue by andrej-g** [fmartinou/whats-up-docker#14]
I've set up the WUD_TRIGGER_HTTP_MYTRIGGER_URL and WUD_TRIGGER_HTTP_MYTRIGGER_METHOD variables, pointing to a valid REST service (created in Node-RED).
The trigger never fires and is also not listed in the web interface, only the SMTP/Gmail trigger is there (and works OK)

The only relevant entries in the log files are:

`{"name":"whats-up-docker","hostname":"49815c7940bc","pid":1,"level":30,"msg":"Register all components for provider http","time":"2020-09-14T06:44:54.541Z","v":0}`
`{"name":"whats-up-docker","hostname":"49815c7940bc","pid":1,"level":50,"msg":"Component http does not exist","time":"2020-09-14T06:44:54.541Z","v":0}`

**Comment by fmartinou** [comment]
Hi,

Just taking a look at the source code and it looks like that the Http Trigger has been accidentally deleted 😕...
Weird, probably a mistake during a refactoring session...

I'm going to quickly fix it; I let you know.

**Comment by fmartinou** [comment]
It's fixed in `2.3.1`; feel free to reopen if need be.
Thanks for your contribution!
