### ISSUE TITLE
registry.gitlab.com support

### ISSUE THREAD

**Issue by alexdelprete** [fmartinou/whats-up-docker#149]
Hi,

I have a couple of containers pulling from `registry.gitlab.com` and not available on ghcr.io unfortunately. Could that registry be supported?

Thanks again for all your work on wud. :)

**Comment by fmartinou** [comment]
Luckily, Gitlab implements the official Docker Registry v2 API so it will be pretty easy to add 🤞 ...
I'm on it 😃

**Comment by fmartinou** [comment]
It's available in version `5.20.0`.

[The documentation related to the Gitlab registry configuration is here](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/gitlab/).

**Comment by alexdelprete** [comment]
Amazing job...users should really appreciate how quick you react to requests. Thanks a lot. :)

**Comment by fmartinou** [comment]
> users should really appreciate how quick you react to requests

It's variable... it mainly depends on my spare time and my mood 😁

**Comment by alexdelprete** [comment]
> It's variable... it mainly depends on my spare time and my mood

Understandable. So I've only been lucky 2 times in a row. :)
