### ISSUE TITLE
how do I create the correct semver version

### ISSUE THREAD

**Issue by ranrinc** [fmartinou/whats-up-docker#152]
Recently snapdrop change its semver ID from `version-53894646` into `version-a96dde25` how do I fix WUD so it will get the latest version?

**Comment by fmartinou** [comment]
If the string is based on the SHA-1 of the git commit, there is no way to distinguish which is the newest ☹️ .
Maybe try to contact the developper of `snapdrop` to understand his release naming logic?
And maybe convince him to move to a standardize semver versioning? 😀
