### ISSUE TITLE
Broken favicon for web ui

### ISSUE THREAD

**Issue by kinglike1337** [fmartinou/whats-up-docker#156]
When creating a bookmark in firefox I noticed an error:
The favicon is not displayed.

After digging around I saw that in the html multiple favicons are linked in the following order:
```html
<link rel="icon" type="image/svg+xml" href="/img/icons/favicon.svg">
<link rel="icon" type="image/png" sizes="32x32" href="/img/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png">
```
Firefox tries to get the first entry `favicon.svg`.
This files does not exist and an html error page is returned with status 200.

Firefox seems to stop here and shows a broken/unknown favicon.
With Chromium the next icon is loaded and is visible.

**Comment by fmartinou** [comment]
I added the missing svg file.
The fix will be available in the upcoming `5.20.2` version.
