### ISSUE TITLE
Sidebar icons

### ISSUE THREAD

**Issue by Depechie** [fmartinou/whats-up-docker#164]
Not sure if intentional or not... but all versions of wud after 5.20.0 have their sidebar icons no longer centered?

<img width="792" alt="Screenshot 2022-09-18 at 13 07 48" src="https://user-images.githubusercontent.com/351693/190899063-b0ca3f6c-595d-4697-a2f6-08b08a693454.png">

**Comment by fmartinou** [comment]
> Not sure if intentional or not.

It's not...
I have to fix it; it's ugly 😳.

**Comment by fmartinou** [comment]
It's fixed and it will be available in the next release.
