### ISSUE TITLE
Entities in HA do not match the update status in WUD

### ISSUE THREAD

**Issue by robertalexa** [fmartinou/whats-up-docker#166]
After leaving this run independently for a few months now, I am still finding discrepancies between what WUD reports and what data is sent to the HA entities.

For example, my HA entities
![image](https://user-images.githubusercontent.com/9019306/192136714-fc50ebaf-aaf0-4fa2-baea-25ec3e69212e.png)

My WUDs:
![image](https://user-images.githubusercontent.com/9019306/192136726-d209ba1b-ccec-46bf-8e3e-0d85fcb8f5d7.png)
![image](https://user-images.githubusercontent.com/9019306/192136738-6264ec4c-6042-4b36-bc93-22234e9c31cb.png)

My configs are fairly default with the 1 exception. One WUD instance is `watchbydefault=false` and instead i am defining `wud.watch=true` in the docker compose file of specific container to be watched - this is of course because my HA instance is a supervised one with addons, so there will be a lot of docker containers that i don't need to track with WUD.

So all 14 containers (8 + 6) exist in HA, but the update status does not match.

Thanks in advance

**Comment by alexdelprete** [comment]
I had a different issue, but I'm thinking maybe it's the same root cause. I wrote about it in another [issue](https://github.com/fmartinou/whats-up-docker/issues/97#issuecomment-1264515203).

Hope it helps.

**Comment by Caros2017** [comment]
I am experiencing the same issue unfortunately. WUD itself is working perfect, but the states in HA doesn't always seem to update correctly.
