### ISSUE TITLE
Logo from Fontawesome

### ISSUE THREAD

**Issue by r0m1CH** [fmartinou/whats-up-docker#168]
Hello,

Thanks for your great work with WUD.

I'm trying to polish my setup by adding icon.
Everything is working smoothly with simpleicon but I cannot make it work with any fontawesome icon.

For example I want to add this one:
<i class="fa-solid fa-radar"></i> (https://fontawesome.com/icons/radar?s=solid&f=classic)

I use this label into my docker compose:
 "wud.display.icon=fas:radar" or  "wud.display.icon=fas-radar"

However, it ends with this html code which is wrong :
< i data-v-0e337868="" aria-hidden="true" class="v-icon notranslate fas fa-fas-fa-radar theme--light"></ i>

Am i missing something ?

Thanks

**Comment by fmartinou** [comment]
Hi,

This icon is apparently a "pro icon" so it's not included in the "@fortawesome/fontawesome-free" package.
![image](https://user-images.githubusercontent.com/16061231/194593562-b1fd6df3-bcca-4767-9857-9f61568f74a0.png)

You can get a very similar icon for free using material-design-icons
```
wud.display.icon=mdi:radar
```

**Comment by r0m1CH** [comment]
oh my god.... I feel so stupid right now sorry for this... you can close it or definitively delete it :-)

**Comment by fmartinou** [comment]
No problem ;)

Thank you for your interest in this project 👍

**Comment by r0m1CH** [comment]
Thanks for your great work / tools !
