### ISSUE TITLE
Is the docker compose trigger supposed to run the YML file supplied or update everything?

### ISSUE THREAD

**Issue by MorpheusUK** [fmartinou/whats-up-docker#177]
Hello,

Sorry if this is a silly question but as I am still setting things up I have been trying out various features. I've read through https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/docker-compose/ several times and as far as I understand it this should invoke the specified compose file when an update is detected (I'm a little unclear on how or if indeed if it relates to specific containers being watched).

Anyway I set it up with a yml file to update portainer (and only portainer), I want to be notified on everything else but want to auto update portainer if this is possible. However it detected an update in jellyfin and proceeded to update that automatically which wasn't part of the yml file. Am I misunderstanding how this trigger works or is that a bug?

The log is below :-

19:19:37.767  INFO whats-up-docker: What's up Docker? is starting (version = 5.21.0)
19:19:37.768  INFO whats-up-docker/store: Load store from (/store/wud.json)
19:19:37.771  INFO whats-up-docker/store: Create Collection app
19:19:37.772  INFO whats-up-docker/store: Migrate data from version undefined to version 5.21.0
19:19:37.773  INFO whats-up-docker/store: Create Collection containers
19:19:37.773  INFO whats-up-docker/prometheus: Init Prometheus module
19:19:37.781  INFO whats-up-docker/registry: Register all components of kind trigger for provider smtp
19:19:37.893  INFO whats-up-docker/trigger.smtp.email: Register with configuration [***REDACTED***]
19:19:37.896  INFO whats-up-docker/registry: Register all components of kind trigger for provider dockercompose
19:19:38.014  INFO whats-up-docker/trigger.dockercompose.portainer: Register with configuration {"prune":false,"backup":true,"file":"/wud/portainer_wud.yml","dryrun":false,"threshold":"all","mode":"simple","once":true,"simpletitle":"New ${kind} found for container ${name}","simplebody":"Container ${name} running with ${kind} ${local} can be updated to ${kind} ${remote}\n${link}","batchtitle":"${count} updates available"}
19:19:39.186  INFO whats-up-docker/registry.ecr: Register with configuration {}
19:19:39.188  INFO whats-up-docker/registry.ghcr: Register with configuration {}
19:19:39.190  INFO whats-up-docker/registry.hotio: Register with configuration {}
19:19:39.192  INFO whats-up-docker/registry.hub: Register with configuration {}
19:19:39.207  INFO whats-up-docker/registry.quay: Register with configuration {}
19:19:40.026  INFO whats-up-docker/watcher.docker.local: Register with configuration {"watchall":true,"cron":"0 1 * * *","socket":"/var/run/docker.sock","port":2375,"watchbydefault":true,"watchevents":true}
19:19:40.027  INFO whats-up-docker/watcher.docker.local: Cron scheduled (0 1 * * *)
19:19:40.035  INFO whats-up-docker/registry: No authentication configured => Allow anonymous access
19:19:40.068  INFO whats-up-docker/authentication.anonymous.anonymous: Register with configuration {}
19:19:40.075  WARN whats-up-docker: Anonymous authentication is enabled; please make sure that the app is not exposed to unsecure networks
19:19:40.082  INFO whats-up-docker/api: Server listening on port 3000 (HTTP)
19:19:41.036  INFO whats-up-docker/watcher.docker.local: Cron started (0 1 * * *)
19:19:41.046  INFO whats-up-docker/watcher.docker.local: Listening to docker events
19:19:54.869  INFO whats-up-docker/watcher.docker.local: Cron finished (4 containers watched, 0 errors, 1 available updates)
19:19:54.902  INFO whats-up-docker/trigger.dockercompose.portainer: Pull image jellyfin/jellyfin:10.8.7 (container=local_jellyfin)
19:19:58.719  INFO whats-up-docker/trigger.dockercompose.portainer: Image jellyfin/jellyfin:10.8.7 pulled with success (container=local_jellyfin)
19:19:58.719  INFO whats-up-docker/trigger.dockercompose.portainer: Stop container jellyfin with id 17975986e728118aa2175d699651f5c67d6887f6b5f7d8d1e3cf6bcbf014054b (container=local_jellyfin)
19:20:02.023  INFO whats-up-docker/trigger.dockercompose.portainer: Container jellyfin with id 17975986e728118aa2175d699651f5c67d6887f6b5f7d8d1e3cf6bcbf014054b stopped with success (container=local_jellyfin)
19:20:02.023  INFO whats-up-docker/trigger.dockercompose.portainer: Remove container jellyfin with id 17975986e728118aa2175d699651f5c67d6887f6b5f7d8d1e3cf6bcbf014054b (container=local_jellyfin)
19:20:02.028  INFO whats-up-docker/watcher.docker.local: Status changed from running to exited (container=local_jellyfin)
19:20:02.789  INFO whats-up-docker/trigger.dockercompose.portainer: Container jellyfin with id 17975986e728118aa2175d699651f5c67d6887f6b5f7d8d1e3cf6bcbf014054b removed with success (container=local_jellyfin)
19:20:02.789  INFO whats-up-docker/trigger.dockercompose.portainer: Create container jellyfin (container=local_jellyfin)
19:20:03.889  INFO whats-up-docker/trigger.dockercompose.portainer: Container jellyfin recreated on new image with success (container=local_jellyfin)
19:20:03.890  INFO whats-up-docker/trigger.dockercompose.portainer: Start container jellyfin (container=local_jellyfin)
19:20:08.439  INFO whats-up-docker/trigger.dockercompose.portainer: Container jellyfin started with success (container=local_jellyfin)
19:20:23.891  INFO whats-up-docker/watcher.docker.local: Cron started (0 1 * * *)
19:20:37.760  INFO whats-up-docker/watcher.docker.local: Cron finished (4 containers watched, 0 errors, 0 available updates)

Thanks for your work on this,

Morpheus

**Comment by fmartinou** [comment]
Hi,

Thank you for reporting this.

You didn't misunderstand how the trigger should work; it's likely a bug.
I'll check it.

**Comment by fmartinou** [comment]
It should be fixed by https://github.com/fmartinou/whats-up-docker/commit/bd7a1ba3826eca8f8bb966453227a09cb43f903d

(it will be part of the next release)
