### ISSUE TITLE
Trigger MQTT - Certificat Authentification

### ISSUE THREAD

**Issue by Pampersfr** [fmartinou/whats-up-docker#181]
hi, 
before thanks a lot for you work of WUD ;-)

I try to use it with MQTT trigger to notify HomeAssistant
i created a self certificat server on MQTT broker  and self certificat client for HomeAssistant and Zigbee2mqtt for example
all works fine...
for WUD do you implement the possibilité to use Client certificat to connect to mqtt broker 
(with possibility to verify or not the certificat because it's self certificat)

thanks a lot 
regards

**Comment by fmartinou** [comment]
Hi,

It's not implemented right now but, for sure, it's feasible.
(I already implemented it on [one of my other projects](https://fmartinou.github.io/teleinfo2mqtt/#/).

The configuration will likely exposes options to :
- Provide the path to the client cert
- Provide the path to the client private key
- Provide the path to the CA chain (for non public CA or self-signed certificates)
- Enable or disable the verification of the MQTT server certificate

**Comment by Pampersfr** [comment]
ok thanks 
yes it's exactly what we need to expose great !!
an idea if it's can be implemented in the last release ? 

another qwickly question : 
i use MQTS url on 8883 port
it's seems that don't work because i use self certificat ?
you confirme? perhaps i forgot something ?
 
`13:13:34.936  INFO whats-up-docker: What's up Docker? is starting (version = latest)
13:13:34.937  INFO whats-up-docker/store: Load store from (/store/wud.json)
13:13:34.995  INFO whats-up-docker/prometheus: Init Prometheus module
13:13:35.008 DEBUG whats-up-docker: Start container metrics interval
13:13:35.088  INFO whats-up-docker/registry: Register all components of kind trigger for provider mqtt
13:13:35.246  INFO whats-up-docker/trigger.mqtt.mosquitto: Register with configuration {"password":"xxxx","user":"wud","url":"mqtts://172.25.0.1:8883","hass":{"enabled":true,"prefix":"homeassistant"},"topic":"wud/container","threshold":"all","mode":"simple","once":true,"simpletitle":"New ${kind} found for container ${name}","simplebody":"Container ${name} running with ${kind} ${local} can be updated to ${kind} ${remote}\n${link}","batchtitle":"${count} updates available"}
13:13:35.390  WARN whats-up-docker/registry: Some triggers failed to register (Error when registering component mqtt (self signed certificate in certificate chain))
13:13:35.391 DEBUG whats-up-docker/registry: Error when registering component mqtt (self signed certificate in certificate chain)
    Error: Error when registering component mqtt (self signed certificate in certificate chain)
        at registerComponent (/home/node/app/registry/index.js:53:15)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 0)
        at async registerTriggers (/home/node/app/registry/index.js:115:9)
        at async Object.init (/home/node/app/registry/index.js:254:5)
        at async main (/home/node/app/index.js:18:5)
`
my docker-compose : 
`version: '3'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    environment:
      - WUD_LOG_LEVEL=DEBUG
      - WUD_SERVER_TLS_ENABLED=true
      - WUD_SERVER_TLS_KEY=/ssl/wud-ca.key
      - WUD_SERVER_TLS_CERT=/ssl/wud-ca.crt
      - WUD_AUTH_BASIC_JREADMIN_USER=xxxxx
      - WUD_AUTH_BASIC_JREADMIN_HASH=$$apr1$$xxxxxxxxxxxxxxxxxxx
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtts://172.25.0.1:8883
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_USER=wud
      - WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=xxxxx

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/xxxxxx/Docker/wud/ssl:/ssl
`
Thanks for your help

**Comment by fmartinou** [comment]
Implemented into https://github.com/fmartinou/whats-up-docker/commit/c23098b1e49e8528811a78d3ee2843c389267efb

(It will be part of the next release)

**Comment by Pampersfr** [comment]
hi 
it's works perfect thanks a lot

**Comment by fmartinou** [comment]
Thank you for your feedback 👍!
