### ISSUE TITLE
Warning log printed in the logs : you're running a deprecated option, checkout https://sort-es.netlify.app/breaking-changes/

### ISSUE THREAD

**Issue by fmartinou** [fmartinou/whats-up-docker#183]
Since `5.22.0`

See https://sort-es.netlify.app/breaking-changes/

**Comment by fmartinou** [comment]
Fixed by https://github.com/fmartinou/whats-up-docker/commit/04cb1161e491806f8085deb35fe5f1e7950d06e5

(will be part of the next release)

**Comment by Philippe6256** [comment]
following an update, the AUTO preset mode seems to have disappeared ?

**Comment by fmartinou** [comment]
I don't really get your point or the relation to this issue.

Can you detail further your issue, please?
