### ISSUE TITLE
Home Assistant: use Update platform instead of binary sensor

### ISSUE THREAD

**Issue by Pjanssen** [fmartinou/whats-up-docker#186]
It would be nice if the Home Assistant (MQTT) trigger could use the "update" platform instead of binary_sensor:
https://www.home-assistant.io/integrations/update/
https://www.home-assistant.io/integrations/update.mqtt/

I guess this could be implemented relatively easily by changing a few things in the MQTT payload. But I think this might also be a breaking change for users depending on the binary_sensors in HA.

**Comment by fmartinou** [comment]
That's a great idea 👍 .

It will be a breaking change, sure, but the impacts won't be too hard to fix for existing users, I think.
(and `wud` will be released as a new major version so people will be warned before upgrading)

=> I try to implement this as soon as possible.

**Comment by fmartinou** [comment]
Implementation in progress...

Here is how it looks as for now:

### Device view
![image](https://user-images.githubusercontent.com/16061231/205486343-f618c31a-d0a3-472a-b04e-49e7f5a9c12b.png)

In this view, unfortunately, an [`entity_picture`](https://www.home-assistant.io/integrations/update.mqtt/#entity_picture) is used by HA to display them (the icon is not displayed).

### Dashboard view (using mushroom update card)
![image](https://user-images.githubusercontent.com/16061231/205486390-9a710262-2de0-43fc-9400-6578439bd05d.png)

Here, icons are used as usual.

### Entity detail
![image](https://user-images.githubusercontent.com/16061231/205486463-ffb4d79c-0c22-4cb6-ad10-c72c6f10d193.png)

Here again, this is the entity_picture which is used...

**Comment by fmartinou** [comment]
If you want to give it a try, you can temporary use the version `fmartinou/whats-up-docker:feature__186_ha_update_platform`
(⚠️ work in progress🚧).

You probably also need to clean up the old binary sensors by yourself or you'll get all sensors twice
(the `binary` ones and the `update` ones).

**Comment by Pjanssen** [comment]
Nice! I just tried it and it mostly seems to work. 
One thing I had expected is for these sensors to show up in the Home Assistant -> System -> Updates screen. I'm not sure what the requirements would be to get this to work though. For comparison, the Zigbee2Mqtt update entities do show up here:
![Screenshot 2022-12-04 at 14 05 43](https://user-images.githubusercontent.com/1184470/205492225-cc47dfcb-7800-4d4c-9abc-f8d48b6bdd3b.png)

Compared to the WUD entity:
![Screenshot 2022-12-04 at 14 05 54](https://user-images.githubusercontent.com/1184470/205492240-b3cfefac-911d-452e-a7df-1c10f7d5aa52.png)

Perhaps these only show up in the updates screen if the integration provides this capability? (Which I suppose is not an obvious thing to do for WUD)

**Comment by fmartinou** [comment]
@Pjanssen 
I confirm your assumption; if a set the `command_topic` property, then the update shows up in the `Updates` page.
![image](https://user-images.githubusercontent.com/16061231/206000143-51b5fb8a-6351-4b78-90d1-8b2fab9b11c1.png)

**Comment by fmartinou** [comment]
If I set any value as a `command_topic` (e.g. `command_topic: ''`), the `install` button will show up and the container will be displayed in the `Updates` page.

But, of, course, if you click on the `install` button, the action will fail (see below)
![image](https://user-images.githubusercontent.com/16061231/206001365-b33f801b-8dfa-4058-875c-eb68da0de300.png)


What solution do you prefer?
1. No `install` button but the updates won't show up in the `Updates` page
2. Fake `install` button which doesn't do anything, but the updates will show up in the `Updates` page
?

**Comment by Pjanssen** [comment]
That's a tricky one. I think it makes sense to only show 'actionable' updates there. Maybe in the future the HA devs will create more features around the update domain.

Having an install button that can only fail does not sound like a good user experience. So I would say keep it as update sensors, which is a nice improvement anyway. But don't provide an update action.

Very nice work 👍

**Comment by fmartinou** [comment]
Just released as [`6.0.0`](https://fmartinou.github.io/whats-up-docker/#/changelog/?id=_600).

**Comment by JvdMaat** [comment]
> > Perhaps these only show up in the updates screen if the integration provides this capability?
> 
> I'm not sure either. Probably, yes 🤔
> 
> To get the `install` button to show up, the [`mqtt command_topic attribute`](https://www.home-assistant.io/integrations/update.mqtt/#command_topic) must be provided.
> 
> For now, `wud` is not capable of updating a container using an `mqtt` command (and as you say, it's maybe not an obvious thing to do for `wud`...).
> 
> But I know it would be a feature welcomed by some users (see #88)

Awesome! Just upgraded to get this, and indeed as per #88, it would be nice to get an Install button.
WUD has the capability, it's just a matter of codifying it so it's not a WUD_TRIGGER_DOCKERCOMPOSE or WUD_TRIGGER_DOCKER trigger, but instead something like:
Docker compose:
WUD_TRIGGER_MQTT_{triggername}_UPDATE_DOCKERCOMPOSE_FILE=/path/docker-compose.yaml
WUD_TRIGGER_MQTT_{triggername}_UPDATE_DOCKERCOMPOSE_PRUNE=true/false
WUD_TRIGGER_MQTT_{triggername}_UPDATE_DOCKERCOMPOSE_BACKUP=true/false
Docker:
WUD_TRIGGER_MQTT_{triggername}_UPDATE_DOCKER=true

It'd be a bit convoluted. But man, that would allow full remote updating on command through HA.
(Assuming the update install command can send something back over MQTT to WUD to action on.. I honestly do not know what the update options are)

**Comment by fmartinou** [comment]
Hi @JvdMaat ,

I'm also convinced that it would be a killer feature to get wud being able to update containers on demand ;)

But I'm wondering if your proposal doesn't mix up multiple concepts 🤔 :
```
WUD_TRIGGER_MQTT_{triggername}UPDATE_DOCKERCOMPOSE_FILE
              ^                            ^
That's a trigger to notify through mqtt  That's another trigger to update containers
```

Use cases:
- some people'd want wud to update a container when it receives an mqtt command message by using the compose trigger
- some other people'd want wud to update a container using the WUD UI by using the docker trigger
- - some other people'd want wud to update a container using the WUD REST API by using the docker trigger
- some other people'd want wud to update a container using the WUD REST API by calling a shell script
- ...

Maybe all these concepts need to be kept separated?
- `TRIGGER`: react to an internal wud event (ie: a new version is available => the trigger must perform an action)
- `COMMAND`: the interface to send commands to wud (REST API, MQTT message...) (ex : update the container X using the COMMAND_HANDLER Y)
- `COMMAND_HANDLER` : the action attached to a command (Docker update, Docker-Compose update, Shell script update...)
?

I need some time to think about a possible design 😁 
What do you think?

**Comment by JvdMaat** [comment]
Personally (I'm a small user), I only have a single command handler (docker compose). However I could see others having multiple systems with different setups in a single WUD. There's actually a lot of value in what you're suggesting (allowing multiple command handlers).
Having said that, I would not use the COMMAND in the WUD container labels, I would reference those in the labels for the container you're monitoring. Here's a sample docker compose: (most required but irrelevant fields left out)
homeassistant:
  labels:
    - wud.tag.include=^\d+\.\d+\.\d+$$
    - wud.link.template=https://github.com/home-assistant/core/releases/tag/$${major}.$${minor}.$${patch}
    - wud.handler=mydockcompose
portainer:
  labels:
    - wud.tag.include=^\d+\.\d+\.\d+$$
    - wud.link.template=https://github.com/portainer/portainer/releases/tag/$${major}.$${minor}.$${patch}
    - wud.handler=straightdocker
wud:
  labels:
    - WUD_HANDLER_mydockcompose_METHOD=dockercompose
    - WUD_HANDLER_mydockcompose_FILE=/path/docker_compose.yaml
    - WUD_HANDLER_straightdocker_METHOD=docker
    - WUD_HANDLER_straightdocker_INFO=<whatever you need to update docker directly>
    - WUD_HANDLER_remotesynology_METHOD=remote
    - WUD_HANDLER_remotesynology_INFO=<whatever needed to update a remote docker>

This way each container can be set up with its own update method (though.. that does require each container to get an additional label, unless there's a good way to implement a default setting). In the above scenario, HA would get updated by the docker compose (Method=docker compose, and the path is specified). I am not familiar enough with straight docker or remote instances to be able to add value to those. But this way each container can get updated the correct way for itself.
This way you're not making it the calling entity's (MQTT, rest API, webhook) problem to know which container gets updated how. Instead it's configured at the point of origin.

**Comment by Inrego** [comment]
Maybe the discussion of such commands and command handlers should be moved to a seperate, open issue? It's easy to forget when it's being discussed in a closed issue. I'd think there's high demand for this.
