### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by stundenblume** [fmartinou/whats-up-docker#187]
Exactly what I was looking for since I use Docker. Love the simple but effective"Container" overview with all relevant information.
Plus: Excellent documentation and beautiful GUI

Thank you very much for your very useful software! Pity It's so hard to find, found it by accident in HA forum.

Is It possible to support you over PayPal instead of "by me a coffee"?

**Comment by fmartinou** [comment]
Hi @stundenblume ,

Thanks a million for your support!

> Pity It's so hard to find, found it by accident in HA forum.

You're absolutely right; this project is still "confidential" 😁 .

Regarding your question; [here is the link to my Paypal account](https://www.paypal.com/donate/?business=ZSDMEC3ZE8DQ8&no_recurring=0&currency_code=EUR).

Best regards!
