### ISSUE TITLE
Updated to 6.0: HA shows binary + update sensors

### ISSUE THREAD

**Issue by alexdelprete** [fmartinou/whats-up-docker#188]
Hi,

From the changelog I expected update sensors to replace binary_sensors, but I see both.

I checked with MQTT explorer and both type of sensors are present. Should we clean the old binary ones manually or is it a bug?

**Comment by fmartinou** [comment]
Hi,

Yes, you need to clean up the old sensors by yourself.
I though mentioned it "bold" in the changelog so that  users don't be surprised 😉

**Comment by alexdelprete** [comment]
There's still one being recreated...we posted at the same time, check above...:)

**Comment by fmartinou** [comment]
![Screenshot_2022-12-08-20-48-42-175_com.brave.browser.jpg](https://user-images.githubusercontent.com/16061231/206553334-0ed09ff3-43b5-41d6-89c9-9bb80d20afb2.jpg)

**Comment by alexdelprete** [comment]
![image](https://user-images.githubusercontent.com/7027842/206553672-9d4f15e9-16cc-4da4-87db-73e318692f5a.png)

**Comment by fmartinou** [comment]
I keep updated the full changelog on the doc, not on GitHub.
But I better understand now why you missed it 🙂

Starting from now, I'll add i. the GitHub release the link to the doc (because I don't want to write the same things at different places) 👍

**Comment by alexdelprete** [comment]
I use WUD to send me the email when a container is updated, and there's the link to the release notes on GitHub, I click that one. :)

Maybe you can add a link to docs in GH notes saying: BREAKING CHANGE, notes here: "link to docs".

**Comment by fmartinou** [comment]
> BTW: I still have one binary sensor appearing in MQTT, with empty config, so it doesn't come up in HA, but it is created in MQTT when I restart WUD 6.0.

I'll perform some tests tomorrow to see if I can reproduce your issue.

**Comment by alexdelprete** [comment]
> I'll perform some tests tomorrow to see if I can reproduce your issue.

I tested it 3-4 times. Put the container down, deleted that binary_sensor, recreated the container of 6.0, and as soon as it started, MQTT explorer showed the binary_sensor again.

No big deal...it has empty config subtopic so it doesn't appear in HA.

Another strange thing I noticed are the icons of the update sensors, I expected the same mdi:docker icon, but this ugly blu big icon appears. The attributes are ok, mdi:docker is there, but still...:)

![image](https://user-images.githubusercontent.com/7027842/206558841-f155b57e-8493-43a6-aa8d-8f4086366066.png)

**Comment by fmartinou** [comment]
About the icons, yes, it is unfortunately how it works on HA end.

You can take a look at the thread associated to this new feature to see all the questions and observations we did about:
https://github.com/fmartinou/whats-up-docker/issues/186

**Comment by alexdelprete** [comment]
> About the icons, yes, it is unfortunately how it works on HA end.

So the mdi:docker icon is different because it's an update sensor and not a binary_sensor?

That looks like an HA bug. I'll check.

For now, thanks a lot...let me know about that ghost binary_sensor. :)

**Comment by alexdelprete** [comment]
The icon problem is due to it showing `entity-picture` vs `icon`. Found out experimenting with a mushroom card:

![image](https://user-images.githubusercontent.com/7027842/206594493-c121a6e7-776c-4aa6-9c37-af3de94f1f02.png)

The difference between the two is only `icon_type`:

```yaml
type: custom:mushroom-update-card
entity: update.wud_container_docker2_esphome
primary_info: name
secondary_info: state
layout: vertical
icon_type: entity-picture
```

```yaml
type: custom:mushroom-update-card
entity: update.wud_container_docker2_esphome
primary_info: name
secondary_info: state
layout: vertical
icon_type: icon
```

I noticed in the update sensor attributes that this was set:

```
entity_picture: https://github.com/fmartinou/whats-up-docker/raw/master/docs/wud_logo.png
```

Maybe if that is set it had precedence on the icon, but I'm just speculating. :)

**Comment by fmartinou** [comment]
Hi,

If I don't provide an `entity_picture`, in the `HA update page` or the `Device configuration page`, instead of seeing an ugly `wud` png image, you'd see an ugly `mqtt` png image, which is worst.

You can observe the same behavior with other integrations.

Example below with `Shelly` devices.
![image](https://user-images.githubusercontent.com/16061231/206660612-22ee0fee-6c84-4023-bd21-0396f3bafb62.png)

On the other hand, when you display the sensor using regular or custom cards, the icon is properly displayed by default.
Example with the `mushroom:update` card
![image](https://user-images.githubusercontent.com/16061231/206660017-d21d1fb2-8852-4c27-982b-d0ff03faa2aa.png)

Example with a standard `entity` card
![image](https://user-images.githubusercontent.com/16061231/206660161-494727b2-e3a1-48a7-91f2-c26beba97295.png)

**Comment by alexdelprete** [comment]
Yes, if you look at my previous post, I used a mushroom-update-card, that's how I understood a little better what the problem could be. Anyway, no big issue...

I'll wait for the feedback on the ghost binary sensor before closing this issue.

**Comment by joostvkempen** [comment]
I've got some strange behaviour on this: updated to 6.0.0 and using HA 2022.12.0 (containerized). Didn't have time to clean the old sensors yet. However it seems the old sensors are still working, and the new ones not?? 

![image](https://user-images.githubusercontent.com/37901988/206666477-009d5283-86f3-4687-b9b7-3bc2922a0edd.png)

![image](https://user-images.githubusercontent.com/37901988/206666745-3c6fbf5a-c97f-4fa4-9c47-d17e99510a05.png)

Are the new sensors not updating as fast as the old ones?

**Comment by fmartinou** [comment]
> Are the new sensors not updating as fast as the old ones?

There is no change regarding how then sensors are updated.

I advise you to start with a clean state when upgrading to 6.0.0 to avoid any side effects:
1. Remove all old sensors on HA
2. Remove local wud state (the state.json file)
3. Start `wud 6.0.0`

**Comment by joostvkempen** [comment]
For now the new sensors are not working at all.... 

![image](https://user-images.githubusercontent.com/37901988/206674956-2c6616ca-6a20-442c-bc44-7421a78e7867.png)

working with containers for a reason: removed sensors in HA, just exited everything and recreated WUD and MQTT containers, still not working:

![image](https://user-images.githubusercontent.com/37901988/206677321-25dac4a8-ac37-4c59-abce-4d6a67431a8c.png)

Where do I find this state.json file?

**Comment by fmartinou** [comment]
> Where do I find this state.json file?

It's only if you have mounted a persistence volume on wud ([see here](https://fmartinou.github.io/whats-up-docker/#/configuration/storage/))

> In the WUD UI the HA update is shown, do I have to change something in the configuration of the triggers and watchers?

Nothing to change.

**Comment by joostvkempen** [comment]
strange? i'm not using persistent storage and I've both WUD and MQTT containers do a rebuild. No updates showing from the sensors, while HA itself and WUD UI do show an update....

I will be updating HA now and wait for the next one... ;-) Sometimes you just need to be patient....

**Comment by fmartinou** [comment]
I've just tested it from scratch and I have none of your issues (no "ghost sensor", no "missing updates").

What I did:

1. Stop `wud`
2. Remove the WUD `/store/state.json`
3. With an mqtt client, I removed the following topics
    - All `wud/container` topics
    - All `homeassistant/binary_sensor/wud*` topics
    - All `homeassistant/update/wud*` topics (only if you already previoously run the 6.0.0 version)
4. Start `wud 6.0.0`

~1 minute later

All the topics are OK so all the HA sensors
- All containers are under `homeassistant/update/*`
- No ghost containers are under `homeassistant/binary_sebnsor/*` 

![image](https://user-images.githubusercontent.com/16061231/206686216-02313f8d-4ec4-47df-87c0-06f572d1e2a2.png)

All sensors are either up-to-date or presenting the newer version
![image](https://user-images.githubusercontent.com/16061231/206686632-7311e474-96df-431e-915a-5d979087fc40.png)

**Comment by alexdelprete** [comment]
> What I did:

I did a deep cleansing of everything like you suggested, basically restarting from scratch. Now everything's ok, no ghost binary_switch.

Thanks.

**Comment by alexdelprete** [comment]
> When I delete the WUD-device in HA, will it recover? I remember doing this earlier with some other device which caused it to be gone forever??

Stop the WUD container, delete the wud.json file.
Open MQTT explorer (or whatever tool you use to manage MQTT) and delete these (if present):
- All wud/container topics
- All homeassistant/binary_sensor/wud* topics
- All homeassistant/update/wud* topics

Restart HA (just to be sure), and verify that you don't have the WUD device anymore. If you have it, delete it. Check also if you have orphan entities.

Once you're sure that everything is clean (MQTT and HA):
- restart the WUD container
- wait 2 minutes
- verify that wud.json file has been recreated
- check with MQTT explorer that topics under homeassistant/update are present
- check that wud topic is present
- open HA and verify under the MQTT integration that WUD device has been recreated
- verify that the new update.wud entities have been recreated

**Comment by joostvkempen** [comment]
pfff, getting really frustrated with myself now..... Did exactly as you described above. Works like a charm (everything was clean, all new entities created), however the entities are still not showing correct values. WUD and MQTT messages are all showing correct update values, the entities in HA however do not reflect them.

For now I've deleted the complete device from HA while running, let's hope I can recover it ;-)

**Comment by joostvkempen** [comment]
My problem seems to be solved with the latest release, thanks for the good work!
