### ISSUE TITLE
OCI index found, but accept header does not support OCI indexes

### ISSUE THREAD

**Issue by adorobis** [fmartinou/whats-up-docker#201]
For two images I'm receiving the following error message and they appear "unknown" in MQTT/HA:
`404 - {"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes"}]}`

Full content of the MQTT message:
```
{
   "id":"3bb0496a7dd842862ef101902ddf497cab110eb91428b25193ee40185715288b",
   "name":"zigbee",
   "status":"running",
   "watcher":"local",
   "display_name":"zigbee",
   "display_icon":"mdi:docker",
   "image_id":"sha256:e762b6caefc7e2130d46ba1f58b9e8742e5f9f521fc946981b672ad9f62a250e",
   "image_registry_url":"https://registry-1.docker.io/v2",
   "image_registry_name":"hub",
   "image_name":"koenkk/zigbee2mqtt",
   "image_tag_value":"latest-dev",
   "image_tag_semver":false,
   "image_digest_watch":true,
   "image_digest_repo":"sha256:2758cbe7358f1d4450769f4fc64970f8c1e580292d86e174353880e6213efe65",
   "image_architecture":"amd64",
   "image_os":"linux",
   "image_created":"2023-01-15T13:29:42.642Z",
   "update_available":false,
   "update_kind_kind":"unknown",
   "error_message":"404 - {\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"OCI index found, but accept header does not support OCI indexes\"}]}"
}
```
I'm getting similar result for the following docker hub images:

`koenkk/zigbee2mqtt:latest-dev`
`nicolargo/glances:latest-full`

**Comment by derekoharrow** [comment]
Same here - also for cadvisor/cadvisor

**Comment by Caros2017** [comment]
Same issue here

**Comment by samcro1967** [comment]
@fmartinou I am seeing this across multiple registries (Docker Hub and ghcr.io).  I tried rolling back to 6.0.0 and 5.22.1 and see the same issue.  Currently have this happening on about 20 out of 100 containers.

**Comment by deluxestyle** [comment]
same issue with deconz container

**Comment by sjtuross** [comment]
I think the same issue mentioned by https://github.com/containrrr/watchtower/pull/1533

**Comment by zimmra** [comment]
> I think the same issue mentioned by [containrrr/watchtower#1533](https://github.com/containrrr/watchtower/pull/1533)

Made a PR https://github.com/fmartinou/whats-up-docker/pull/208

Resolved the OCI issues in my setup

**Comment by samcro1967** [comment]
@zimmra I tested your PR and it has cleared up the OCI errors and I am seeing all containers with updates available.  The docker compose automation though is not working and updating the containers.  Here is what I am seeing in the logs related to docker compose.

```
22:53:35.363 DEBUG whats-up-docker/trigger.dockercompose.wud: Cannot read properties of undefined (reading 'indexOf')
        at Dockercompose.getNewImageFullName (/home/node/app/triggers/providers/docker/Docker.js:233:25)
        at Dockercompose.mapCurrentVersionToUpdateVersion (/home/node/app/triggers/providers/dockercompose/Dockercompos
.js:154:26)
        at /home/node/app/triggers/providers/dockercompose/Dockercompose.js:79:38
        at Dockercompose.triggerBatch (/home/node/app/triggers/providers/dockercompose/Dockercompose.js:79:14)
        at async Dockercompose.handleContainerReports (/home/node/app/triggers/providers/Trigger.js:75:17)
22:53:57.885 DEBUG whats-up-docker/trigger.dockercompose.wud: Run trigger batch
22:53:58.006 DEBUG whats-up-docker/trigger.dockercompose.wud: Get ghcr registry manager
22:53:58.006 DEBUG whats-up-docker/trigger.dockercompose.wud: Get hub registry manager
22:53:58.006 DEBUG whats-up-docker/trigger.dockercompose.wud: Get hub registry manager
22:53:58.006 DEBUG whats-up-docker/trigger.dockercompose.wud: Get hub registry manager
22:53:58.006 DEBUG whats-up-docker/trigger.dockercompose.wud: Get hub registry manager
```

**Comment by fmartinou** [comment]
Hi,

Thank for reporting this issue, the analysis and the fix 👍 .

I merge the PR from @zimmra on a branch to have the integration tests running on it.
And if there are no regressions, then I release it very quickly to get you fixed!

**Comment by samcro1967** [comment]
Realized this morning I was still running 5.22.1 as I was testign older versions.  Not seeing the same issues with latest.

**Comment by fmartinou** [comment]
It's fixed.

The release `6.0.2` is on the way.

**Comment by adorobis** [comment]
Many thanks!
