### ISSUE TITLE
[Request] Watcher placeholder in trigger body template

### ISSUE THREAD

**Issue by jpbaril** [fmartinou/whats-up-docker#204]
I have WUD watching a few hosts and I would like that the notifications indicate on which host is the updatable container.
If we had a "{watcher}" placeholder I could include that in notifications body template.
Thanks

**Comment by fmartinou** [comment]
Hi @jpbaril ,

Your request makes perfectly good sense 👍 .

=> I'll add it.

**Comment by fmartinou** [comment]
It's fixed (https://github.com/fmartinou/whats-up-docker/commit/4b87ac0a33569a0a7c2c2f90b299e6f9ff673cc2).

The release `6.0.2` is on the way.
