### ISSUE TITLE
Error The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### ISSUE THREAD

**Issue by Alindil** [fmartinou/whats-up-docker#233]
Hi,

on several containers I have the error: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

Example of container: Home assistant, plex, homepage, overseerr

![image](https://user-images.githubusercontent.com/30829631/221132370-ca168895-cc60-4b1a-a11b-b782c248fe3e.png)

**Comment by fmartinou** [comment]
Hi,

This issue has also been detected by another user:
https://github.com/fmartinou/whats-up-docker/issues/218

I'll take a look to understand what's going wrong.

In the mean time, please do not use the `wud` `latest` tag but the latest release (`6.0.2`) which is not affected by this bug.

**Comment by fmartinou** [comment]
Closing as duplicate of https://github.com/fmartinou/whats-up-docker/issues/252

**Comment by fmartinou** [comment]
Fix released as `6.1.0`
