### ISSUE TITLE
[feature request] Overview sensors for Home Assistant

### ISSUE THREAD

**Issue by devmills** [fmartinou/whats-up-docker#236]
Hi, first of all many thanks for this project, it's very helpful indeed.
I unfortunately cannot find a way to see this easily, apologies if it already exists somewhere. I think it would be useful to have additional update sensors appear in Home Assistant for all containers monitored by WUD.
E.g. a binary (or update) sensor that simply indicates "Updates Available" or not.
Additionally a sensor of how many container updates are available as a number.

The information is clearly available in the WUD UI, but it would be nice to have this info in HA. My end goal is to feed this as a push notification periodically. 
![image](https://user-images.githubusercontent.com/97687584/223200770-b530906f-eeb0-4564-8972-f0ee7459c3d6.png)

I have many containers and would like a generic "updates are available" notification for me to review the more detailed list. 

Many thanks!

**Comment by fmartinou** [comment]
Hi,

I understand the need; I'll try to add these 2 global sensors.

**Comment by blackstardlb** [comment]
Would also be awesome if we could have a sensor / api endpoint to see if wud is currently watching containers.

**Comment by fmartinou** [comment]
Hi,

I added sensors at 2 different levels:
- Global sensors
- Watcher sensors (i.e. sensors per watched `host`)

![image](https://user-images.githubusercontent.com/16061231/229299641-cdb0c540-3b79-4465-a584-c50e3fdf1491.png)
