### ISSUE TITLE
Manual image upgrade from the UI

### ISSUE THREAD

**Issue by ionutbaban** [fmartinou/whats-up-docker#237]
Is there a way to manually trigger the image update from the UI?
I see the Delete button, but no Update option
![image](https://user-images.githubusercontent.com/3975080/223826575-2f722977-e5cb-4598-9c0d-b9903c603841.png)

**Comment by fmartinou** [comment]
Hi,

It's not implement at this time.

It's a feature request from a long time...

I'll probably add it sooner or later ^^.

(To be honest, if it's not implemented right now, it's more because of design issues than technical issues).

**Comment by fmartinou** [comment]
Related to:

- https://github.com/fmartinou/whats-up-docker/issues/210
- https://github.com/fmartinou/whats-up-docker/issues/88

**Comment by ionutbaban** [comment]
ok, thanks for letting me know
I will close this issue as there are two other ones open
I did a bit of searching, but could not find them initially
