### ISSUE TITLE
Trigger MQTT - Add Client ID variable

### ISSUE THREAD

**Issue by Pampersfr** [fmartinou/whats-up-docker#244]
hi, 

it's possible to add Client ID when we use MQTT Trigger ?
i use docker compose so, in environment variable ?
today it's random client id that is used : 
`1679329796: New client connected from xxxxxxxx as **mqttjs_598a6124** (p2, c1, k60, u'MQTTClient').`

thanks a lot

**Comment by Pampersfr** [comment]
Hi
`Is it just because it's not obvious to correlate this random mqttjs_xxx id to wud?`
yes exactly

 `For example wud_$uid?`
yes it's perfect this 

Thanks a lot

**Comment by fmartinou** [comment]
By the way, it's already released (`6.1.0`).

**Comment by Pampersfr** [comment]
and already implemented ;-)
thanks a lot
