### ISSUE TITLE
After updating image, old image persists in WUD web GUI

### ISSUE THREAD

**Issue by jasongordon** [fmartinou/whats-up-docker#25]
After I update the version tag in my  `docker-compose.yml` file and then issue the `docker-compose up -d` command, the new version appears as a new line in WUD and the old version persists.

![wud2](https://user-images.githubusercontent.com/2027525/104449527-b9fb1180-556c-11eb-9bca-a212f4abb635.PNG)

**Comment by fmartinou** [comment]
It's fixed  in version `3.2.1`.
