### ISSUE TITLE
Unusual warning with fixed version image

### ISSUE THREAD

**Issue by mattdale77** [fmartinou/whats-up-docker#250]
I am getting the following warning on startup. It took me a while to uncover what container it was but it is a mariadb container fixed to a specific release.

WARN whats-up-docker/watcher.docker.local: Cannot get a reliable tag for this image [sha256:aac2cf878de917be8d8f9824756ec5850ba7ccbfc71eaa85346635a50bd7eb89]

From the docker-compose.yml

 image: mariadb:10.6

I'm not sure if this is a bug or an expected warning so I'll bring it up, just in case

**Comment by fmartinou** [comment]
Hi,

If you're pinning a container version (e.g. `sha256:aac2cf878de917be8d8f9824756ec5850ba7ccbfc71eaa85346635a50bd7eb89`), there is no way for `wud` to determine whether there is an update available or not.

Update candidate resolution can only work when using tags.
That's why you get this warning.

**Comment by mattdale77** [comment]
Is there a way to exclude this container or should I just ignore the warning?

**Comment by fmartinou** [comment]
You can include/exclude containers using labels:
https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels

Examples:
- https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=include-specific-containers-to-watch
- https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=exclude-specific-containers-to-watch

**Comment by mattdale77** [comment]
Perfect. Thank you.

I added the following label to the container

wud.watch=false
