### ISSUE TITLE
Error with containers from ghcr.io (public images)

### ISSUE THREAD

**Issue by Jefe2** [fmartinou/whats-up-docker#252]
I have WUD configured to access public images from `ghcr.io`.  Where it had previously worked, an error is now generated when a `ghcr.io` image is watched.  The error started happening when this code change was implemented a few weeks ago: `[GHCR] - Fix ghcr bearer authentication`.

This error is being generated with any container from `ghcr.io`:
`WARN whats-up-docker/watcher.docker.local: Error when processing (The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined) (container=local_wud)`.

My systems are `ARM64` and `AMD64`.  The issue occurs on both.

**Comment by fmartinou** [comment]
Released as `6.1.0`
