### ISSUE TITLE
Variables available for triggers

### ISSUE THREAD

**Issue by mattdale77** [fmartinou/whats-up-docker#256]
Is there somewhere I can view all the set variables for triggers?

In particular I'd be interested in the actual version numbers. The defaults ($local and $remote) shows a long hash which is pretty meaningless

**Comment by fmartinou** [comment]
It may depend on the exact trigger you use but the variable used to render the title/body templates are listed here
https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/

- ${id}
- ${name}
- ${kind}
- ${watcher}
- ${semver}
- ${local}
- ${remote}
- ${link}

> In particular I'd be interested in the actual version numbers

The version numbers are present on the `semver` variable if available.

**Comment by dougmaitelli** [comment]
This is definitely not working:
Available update recognizes semver properly
![image](https://github.com/fmartinou/whats-up-docker/assets/1277391/cf15dc68-cae9-475e-a07c-cb62710b0c2b)

Trigger uses semver for notification:
![image](https://github.com/fmartinou/whats-up-docker/assets/1277391/56f78faf-12e8-4fc6-b975-10a477838c2e)

Actual value delivered:
![image](https://github.com/fmartinou/whats-up-docker/assets/1277391/581d7987-bb5d-4a60-b18d-7d3ad165f4bb)

**Comment by fmartinou** [comment]
See discussion on https://github.com/fmartinou/whats-up-docker/issues/309
