### ISSUE TITLE
Feature request: Create trigger through Telegram

### ISSUE THREAD

**Issue by Northguy** [fmartinou/whats-up-docker#257]
I would like to abandon the automated updating through Watchtower and move to Whats Up Docker. Would it be possible to create a trigger through Telegram in the same way that Watchtower is sending triggers through telegram? 

I think that Watchtower has Shoutrrr integrated in it's container. If it is possible to use WUD to communicate through a separate Shoutrrr container this would also be perfectly fine.

**Comment by fmartinou** [comment]
Hi,

I'll see to provide a direct integration of Telegram 👍 

In the meantime, you can already send messages with telegram using the [Apprise trigger](https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/apprise/).

(you'll need to deploy an additional Apprise container though)
[See here Apprise telegram integration](https://github.com/caronc/apprise/wiki/Notify_telegram)
