### ISSUE TITLE
Feature: Dark Mode

### ISSUE THREAD

**Issue by modem7** [fmartinou/whats-up-docker#258]
Would it be possible to implement a dark mode? 

The white GUI is quite shocking on the eyes during late night sessions. 

Thanks!

**Comment by fmartinou** [comment]
Hi,

It's a good suggestion; I'll add it to my to-do list 👍.

**Comment by fmartinou** [comment]
Preview
![image](https://user-images.githubusercontent.com/16061231/229581610-3db680ca-45c4-4120-95e2-d674ca12aa61.png)

(the light/dark mode toggle is at the bottom of the left menu)

**Comment by modem7** [comment]
Oh dats sexy!

Perfect!

**Comment by fmartinou** [comment]
In addition, the value of the settings (dark/light) is stored into the Browser local storage to persist the preference.
