### ISSUE TITLE
[Feature request] Homepage integration

### ISSUE THREAD

**Issue by Artnal** [fmartinou/whats-up-docker#270]
Hi there, 

Thanks a bunch for your work on this tool, it's exactly what I was looking for!

I was wondering whether an integration into [Homepage](https://gethomepage.dev/en/installation/) ([Github](https://github.com/benphelps/homepage)) though a widget would be an option. Ideally, the widget would mainly show [Containers] and [Updates]. I'm not sure what the process is for integration into Homepage, but that would be neat. 

Cheers

**Comment by thehijacker** [comment]
This is already added in Homepage as widget:

https://gethomepage.dev/en/services/whatsupdocker/

This is how it looks:

![image](https://user-images.githubusercontent.com/13857043/236608516-c24abb52-9144-4b6f-97c6-c0f8c1f1ed16.png)

**Comment by fmartinou** [comment]
Awesome! 🤩 

Many thanks to @RichyHBM for having coded this Homepage integration 👍
