### ISSUE TITLE
Feature Request: support for gitea / forgejo API

### ISSUE THREAD

**Issue by alexdelprete** [fmartinou/whats-up-docker#283]
Hi @fmartinou,

I'm running a [forgejo](https://forgejo.org/) instance in my homelab. forgejo is a soft-fork of gitea, so it uses the same API basically.

The forgejo project is hosted on codeberg.org public registry (it uses forgejo as backend).

I was wondering if WUD could support the gitea/forgejo API, so both public and private registries could be supported.

The API is here: https://try.gitea.io/api/swagger (forgejo API should be the same, it's here: https://codeberg.org/api/swagger).

Thanks a lot.

**Comment by fmartinou** [comment]
Hi @alexdelprete ,

The support for both `gitea` and `forgejo` has been added!
- https://fmartinou.github.io/whats-up-docker/#/configuration/registries/gitea/
- https://fmartinou.github.io/whats-up-docker/#/configuration/registries/forgejo/

It's available from version `6.3.0`

**Comment by alexdelprete** [comment]
Thank you so much @fmartinou, hope it didn't take too much of your time implementing this.

I tested it both in my forgejo homelab instance and codeberg.org, everything seems to be working fine. :)

I have 2 questions:

1. I'd like to use both my private forgejo instance and codeberg.org. Is this a supported use case? 2 instances of the same registry type.
2. Forgejo and Gitea support Application Access Tokens with fine grained scope support, would it be possible to also support that?

![image](https://github.com/fmartinou/whats-up-docker/assets/7027842/8eede880-1a8b-49ed-bd8f-31d8c7251f99)

Thank you again for this. :)

**Comment by fmartinou** [comment]
Hi @alexdelprete ,

Thank you for the feedback. 👍 

> I'd like to use both my private forgejo instance and codeberg.org. Is this a supported use case? 2 instances of the same registry type.

Unfortunately it's not supported.
=> It makes sense; I add it to my TODO list


> Forgejo and Gitea support Application Access Tokens with fine grained scope support, would it be possible to also support that?

=> I'll try to implement it.

**Comment by alexdelprete** [comment]
Thank you so much for your support.
