### ISSUE TITLE
Duplicati development version label problem

### ISSUE THREAD

**Issue by Pampersfr** [fmartinou/whats-up-docker#289]
hi, 

i try to configure wud for duplicati development version to inform me in HA
i have installed : image: lscr.io/linuxserver/duplicati:development-version-v2.0.6.105-2.0.6.105_canary_2023-04-09
in docker compose i put this label : 
`    labels:
      - 'wud.tag.include=^development-version-v\d+\.\d+\.\d+\.\d+-\d+\.\d+\.\d+\.\d+_canary$$'
`
but in HA it's tell me that i'm up to date... but there is a new version in duplicati repository
(development-version-v2.0.6.106-2.0.6.106_canary_2023-05-03)
![image](https://github.com/fmartinou/whats-up-docker/assets/83452825/5b46e361-f117-4b11-a95a-7b6f15b26b7e)

i don't understand, bad regex in label ?

thanks for your help
regards

**Comment by dswd** [comment]
(I am not a dev, just a user)

Yes, your regex is wrong. You should use `wud.tag.include=^development-version-v\d+\.\d+\.\d+\.\d+-\d+\.\d+\.\d+\.\d+_canary_\d+-\d+-\d+$` to include this specific naming schema.
However, are you sure you specifically want those development versions? If you just want the latest version regardless whether it is development or a release, you can use hash based checking.
I normally use the include label the limit the labels to only releases and exclude all those development versions.

**Comment by fmartinou** [comment]
I'm closing the issue because of inactivity.
(and it relates on `regex` expressions, not on `wud` misbehaviour)
