### ISSUE TITLE
Blank openid access

### ISSUE THREAD

**Issue by webysther** [fmartinou/whats-up-docker#290]
Hi, great project! But sometimes I got a blank login page:

![image](https://github.com/fmartinou/whats-up-docker/assets/750007/74b308b2-20d5-4646-a548-e305a6f14345)

I have openid authelia and works well in other services in my homelab, on WUD the time in time I got this screen without any error in log or in frontend console, when restart the container works again.

Any advice?

**Comment by fmartinou** [comment]
Hi,

This happens when `wud` starts before `Authelia`.
At the startup, `wud` calls `authelia` to discover some Openid metadata.
When the call fails, `wud` disables the Authelia integration; that's why you see a blank login page... until you restart `wud`.

**Comment by webysther** [comment]
Make sense, I need to restart authelia because [dont support reload yet](https://github.com/authelia/authelia/issues/1275)
