### ISSUE TITLE
Possibility to trigger update from external?

### ISSUE THREAD

**Issue by loeffelpan** [fmartinou/whats-up-docker#292]
I would like to ask a question.
My usecase is to notify with Homeassistant via Webhook or MQTT on container updates.

Now I would prefer to trigger updates from Homeassistant rather than use a docker trigger to update automatically.

Is that possible?

**Comment by fmartinou** [comment]
Hi @loeffelpan ,

It' not possible at this time but it's planned.
(please see the feature request #210)
