### ISSUE TITLE
Update docker per ui/api/mqtt

### ISSUE THREAD

**Issue by newmindJP** [fmartinou/whats-up-docker#304]
I love this project - it is exactly what I'm looking for since a while - specially the MQTT and home-assistant integration is a great adder.
I know this was mainly developed for showing the current status, but it would be an excellent feature if an update is shown if I can trigger the update of the docker-image (I always use latest) per ui/api or even better per mqtt from home-assistant

**Comment by aheath70** [comment]
+1 for this please. 

I would love to have the ability to review what the changes are in a new version and then "one button click" to upgrade it from HA.
