### ISSUE TITLE
Semver not returning proper value on triggers

### ISSUE THREAD

**Issue by dougmaitelli** [fmartinou/whats-up-docker#309]
Available update recognizes semver properly
![image](https://github.com/fmartinou/whats-up-docker/assets/1277391/35aef723-de5f-4264-a0f0-7e7cfec9042b)

Trigger uses semver for notification:
![image](https://github.com/fmartinou/whats-up-docker/assets/1277391/786be559-9bf1-4414-b202-8bd974877808)

Actual value delivered:
![image](https://github.com/fmartinou/whats-up-docker/assets/1277391/f258cb37-93a7-4b2c-9c4a-720d1c3cac87)

**Comment by fmartinou** [comment]
The `semver` placeholder is not meant to return the available version but the _"semver difference"_ between the current version and the available version. (i.e. `major`, `minor`, `patch`).

The doc probably deserves some kind of clarification 🤔 .

You can update your body template to `Container ${name} can be updated to ${remote}` and you should be fine.

**Comment by dougmaitelli** [comment]
@fmartinou Thanks for the clarification, yeah I feel like the term "semver" in this case is confusing since in the UI it shows the actual version tag besides the label "semver". This could be called something like "semverdiff" I don't know, but just more clarification on the docs would help too.

Thanks,
