### ISSUE TITLE
Change listening port

### ISSUE THREAD

**Issue by IIIdefconIII** [fmartinou/whats-up-docker#320]
HI,

I have multiple containers runing, one, like homepage runs on port 3000 already, how can i change this? in the docker compose changing to another port doesnt work cause its hard coded

Thanks!

**Comment by fmartinou** [comment]
Hi,

It's not hard-coded; there is an environment variable to provide the port to bind.

The related documentation:
https://fmartinou.github.io/whats-up-docker/#/configuration/server/

The related example:
https://fmartinou.github.io/whats-up-docker/#/configuration/server/?id=set-http-listener-port-to-8080

Then just map this container port to the host port you wish 🙂 .

**Comment by IIIdefconIII** [comment]
Thanks for the quick respons. I could find this earlier and I Will implent this later today

**Comment by IIIdefconIII** [comment]
Thanks, got it working!

  wud:
    container_name: wud
    image: fmartinou/whats-up-docker:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 8085:8085
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK   
      TZ: Europe/Amsterdam
      WUD_SERVER_PORT: 8085         
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    labels:
      ## Pullio
      org.hotio.pullio.notify: "true"
      org.hotio.pullio.update: "true"

**Comment by IIIdefconIII** [comment]
`  wud:
    container_name: wud
    image: fmartinou/whats-up-docker:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 8085:8085
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK: $UMASK   
      TZ: Europe/Amsterdam
      WUD_SERVER_PORT: 8085         
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    labels:
      ## Pullio
      org.hotio.pullio.notify: "true"
      org.hotio.pullio.update: "true"`

**Comment by IIIdefconIII** [comment]
![image](https://github.com/fmartinou/whats-up-docker/assets/9917659/5ea44951-2871-423e-bd48-eee2856e8cdc)

**Comment by IIIdefconIII** [comment]
!archive
