### ISSUE TITLE
Common config variables with existing variables???

### ISSUE THREAD

**Issue by Ejz9** [fmartinou/whats-up-docker#322]
All I want is for my containers to Auto Update. My understanding? Use:

- WUD_TRIGGER_DOCKER_AUTOUPDATE_MODE=batch_PRUNE=true

although after applying, WUD does not understand the mode and says it needs to be simple or batch. If I remove the PRUNE part then it works. I want to prune the images though after containers are updated. HELP! I have tried putting quotations around "batch" and "true" yet it doesn't allow. The documentation even states: "This trigger also supports the common configuration variables." Yet I cannot get it to work. Thanks!

**Comment by Ejz9** [comment]
SOLVED= I realized that I can just restate the triggers name to apply another variable. I think I remember reading this in the documentation. It's not explicitly clear though.

**Comment by fmartinou** [comment]
I'm glad to see you figured out 🙂
