### ISSUE TITLE
Bug or misconfiguration : Digest information instead of version number

### ISSUE THREAD

**Issue by manubob** [fmartinou/whats-up-docker#325]
Hello,

I'm trying your application for the first time and after several tests I'm not able to show the version number of my current containers, (available version as well) I've only digest information that's not relevant for me.

I'm asking you because I don't find the solution, here my docker-compose of WUD :
version: '3'
services:
    whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    environment:
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - WUD_TRIGGER_TELEGRAM_1_BOTTOKEN=blablabla
      - WUD_TRIGGER_TELEGRAM_1_CHATID=-blablabla
      - WUD_TRIGGER_TELEGRAM_1_MODE=SIMPLE
      - WUD_TRIGGER_TELEGRAM_1_ONCE=FALSE
      - WUD_TRIGGER_TELEGRAM_1_THRESHOLD=all
      - TZ=Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/wud:/store
    ports:
      - 3555:3000

And few compose from my containers :
version: '3.3'
services:
    linuxserver:
        container_name: sonarr
        ports:
            - 8989:8989
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Europe/Paris
        labels:
        - wud.display.name=sonarr
        - wud.display.icon=mdiTelevisionBox
        - wud.tag.include=^v[0-9]\d*.[0-9]\d*.[0-9]\d*.[0-9]\d*-ls[0-9]\d*$
        - wud.watch=true
        volumes:
            - /volume1/docker/sonarr:/config
            - /volume1/Videos/Films:/movies
            - /volume1/Videos/Series.TV:/tv
            - /volume1/Videos/Downloads:/downloads
        restart: always
        image: ghcr.io/linuxserver/sonarr

version: '3.3'
services:
    rdtclient:
        image: rogerfar/rdtclient
        container_name: rdtclient
        labels:
        - wud.display.name=rdtclient
        - wud.display.icon=mdiMonitorDashboard
        - wud.tag.include=^v[0-9]\d*.[0-9]\d*.[0-9]\d*$$
        - wud.watch=true
        environment:
            - PUID=1026
            - PGID=100
        volumes:
            - /volume1/Videos/Downloads:/data/downloads
            - /volume1/docker/rdt-client:/data/db
        restart: always
        ports:
            - '6500:6500'

Is there something wrong or missing ?
<img width="1855" alt="14102023" src="https://github.com/fmartinou/whats-up-docker/assets/19492305/987caf90-400e-4d90-a431-521f68720a59">

Thank you !

**Comment by fmartinou** [comment]
Hi,

To have version numbers to work, you need to run immutable tags and not mutable tags like `latest` is.
For `sonarr`, by example, you must run the image
- `ghcr.io/linuxserver/sonarr:3.0.10`
- and neither ~`ghcr.io/linuxserver/sonarr:latest`~
-  nor ~`ghcr.io/linuxserver/sonarr`~

**Comment by manubob** [comment]
Hi,
Thank you, I can see now the version number, however I'm facing to two issues with the two containers I described in my first post.
rdtclient -> There is a new version 2.0.40 but WUD doesn't see it.
sonarr -> The version available is a oldest version comparing to the current installed.

Something wrong again :) ?

Thanks[
<img width="1855" alt="15102023_2" src="https://github.com/fmartinou/whats-up-docker/assets/19492305/47301a4a-416d-4c12-9668-9ce81ac6cec6">
<img width="1855" alt="15102023" src="https://github.com/fmartinou/whats-up-docker/assets/19492305/f0f798c2-23cb-4605-b33a-bd43a45013ae">
](url)

**Comment by fmartinou** [comment]
Hi,

Regarding `rdtclient`, that's because your filter regex is wrong.
Your regex matches `^v[0-9]\d*.[0-9]\d*.[0-9]\d*$$` whereas there is no leading `v` in the tag.
Try with `^\d+\.\d+\.\d+$$`

Regarding `sonarr`, that's because their tag format is shitty; it doesn't implement [semver versioning](https://semver.org/) so the tags cannot be compared to find which is grater/lower.

You can circumvent that by adding a function that will map the original tag name to something else that will implement semver.
To do that, you must add a `wud.tag.transform` label on your container as explained [in the documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=transform-the-tags-before-performing-the-analysis).

**Comment by manubob** [comment]
Thanks a lot for your support ;)
