### ISSUE TITLE
WUD_REGISTRY_HUB_AUTH__FILE not working, WUD_REGISTRY_HUB_AUTH working correctly

### ISSUE THREAD

**Issue by ChevySSinSD** [fmartinou/whats-up-docker#343]
I am not able to get WUD_REGISTRY_HUB_AUTH__FILE to work properly, however, I am able to get WUD_REGISTRY_HUB_AUTH to work and also have WUD_REGISTRY_GHCR_TOKEN__FILE working properly in the same setup.  Here is the relevant docker-compose.yml (I have verified the "longsecretstringbase64" text is the same in the file as in my docker-compose.yml, so I'm at a loss of what is going on:

```
volumes:
  - /home/eric/docker/secrets:/secrets:ro            # Directory for secrets
environment:
  - WUD_REGISTRY_GHCR_TOKEN__FILE=/secrets/WUD_REGISTRY_GHCR_TOKEN  #This works
  - WUD_REGISTRY_HUB_AUTH=longsecretstringbase64                    #This also works
  - WUD_REGISTRY_HUB_AUTH__FILE=/secrets/WUD_REGISTRY_HUB_AUTH      #This does not work
```

**Comment by fmartinou** [comment]
Hi,

Can you set set the log level to DEBUG and restart the app to see if, by chance, more details are printed?

**Comment by ChevySSinSD** [comment]
Here's what I get.  I tested the contents of my /secrets/WUD_REGISTRY_HUB_AUTH in a Base64 decoder, it is valid Base64 string and it shows my userid as expected in the decoded format.
```
18:54:12.246 DEBUG whats-up-docker/registry: Error when registering component hub ("auth" must be a valid base64 string)
18:54:12.244  WARN whats-up-docker/registry: Some registries failed to register (Error when registering component hub ("auth" must be a valid base64 string))
    Error: Error when registering component hub ("auth" must be a valid base64 string)
        at async Promise.all (index 1)
        at async registerRegistries (/home/node/app/registry/index.js:149:9)
        at async Object.init (/home/node/app/registry/index.js:258:5)
```

**Comment by ChevySSinSD** [comment]
Just FYI, here's the log showing it works when I have this in docker compose instead:
`  - WUD_REGISTRY_HUB_AUTH=longsecretstringbase64                    #This also works
`
Log output:
```
19:12:38.770  INFO whats-up-docker/registry.hub: Register with configuration {"auth":"Y**************************************************************r"}
```

**Comment by ChevySSinSD** [comment]
Apologies, I figured it out, nano was putting a new line in my file, I removed it and all is working properly.

https://github.com/authelia/authelia/issues/1956#issuecomment-831698517
