### ISSUE TITLE
[FR] Watch Stopped Containers

### ISSUE THREAD

**Issue by ameer1234567890** [fmartinou/whats-up-docker#348]
Currently, WUD only watches running containers. This is a feature request to include stopped containers as well. Maybe a setting/toggle for this option.

**Comment by fmartinou** [comment]
Hi,

This option already exists; `WUD_WATCHER_{watcher_name}_WATCHALL`
[Please see the doc here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/)

It should suit your need.
