### ISSUE TITLE
Make SMTP username and password optional

### ISSUE THREAD

**Issue by kuya1284** [fmartinou/whats-up-docker#351]
There are people like me who may have a local SMTP server (i.e. Postfix) running that doesn't require authentication. Thus, both `WUD_TRIGGER_SMTP_{trigger_name}_USER` and `WUD_TRIGGER_SMTP_{trigger_name}_PASS` really should be optional.

As an interim solution, I just set both to some random string (i.e. `null`).

**Comment by ptr727** [comment]
Yes please, I run postfix as am anonymous SMTP forwarder to gmail, there is no email and password, and if they are provided auth will fail.

**Comment by fmartinou** [comment]
Hi,

It's fixed; it will be part of the next release.

**Comment by kuya1284** [comment]
Thank you, @fmartinou.
