### ISSUE TITLE
Necessary Docker API Section Access

### ISSUE THREAD

**Issue by jrbarronumd** [fmartinou/whats-up-docker#354]
Hello, and thanks for sharing your work!

I'm trying to get set up with WUD, and the local machine is going well.  I also have a remote server on my network running a few things that I'd like to watch.  I've been using [Homepage](https://github.com/gethomepage/homepage) to access the Docker API for some time now, with [this](https://github.com/Tecnativa/docker-socket-proxy) docker socket proxy container by Tecnativa, recommended by the Homepage docs.  The idea behind the proxy container is to selectively expose the socket externally, and it is very conservative as a default.

There is a [list](https://github.com/Tecnativa/docker-socket-proxy?tab=readme-ov-file#grant-or-revoke-access-to-certain-api-sections) of API sections that can be allowed by the proxy container - Is there a defined list of calls used by WUD?  I'm guessing the conservatism will have to be pretty well shredded if I want WUD to update containers, but right now it can't even see the socket at all, and I'm not seeing much detail in the logs, other than the snippet below.  Any suggestions are greatly appreciated.

```
19:10:24.680  WARN whats-up-docker/watcher.docker.my-server:
    Error when trying to get the list of the containers to watch ((HTTP code 403) unexpected - <html><body><h1>403 Forbidden</h1>
    Request forbidden by administrative rules.
    </body></html>
    
     )
```

Thanks again!

**Comment by fmartinou** [comment]
Hi,

I haven't tested it but I'd say:
- CONTAINERS
- ALLOW_START (containers/id/start) (if you want wud to update your containers)
- ALLOW_STOP (containers/id/stop) (if you want wud to update your containers)
- IMAGES
- INFO

**Comment by jrbarronumd** [comment]
Awesome, thanks!  I'll test it out soon and post back here with findings.

Is this the best place for questions (adding question tag next time)?  I have one more question about capabilities, but I haven't finished searching yet to make sure it isn't covered in Docs or elsewhere.  I found your Home Assistant forum thread, but it seems pretty dormant...

**Comment by fmartinou** [comment]
> Is this the best place for questions (adding question tag next time)? 

Yes, no problem.
GitHub issues are fine to me to track questions as well 👌

**Comment by jrbarronumd** [comment]
Thank you again @fmartinou for the quick response!  It seems like everything I'm planning to use is working with the suggested API sections.  I am not using WUD to update containers directly, so I can't speak to that.  If I come across any new access errors, I'll open another question.
