### ISSUE TITLE
Wrong digest returned when architecture is not amd64

### ISSUE THREAD

**Issue by fmartinou** [fmartinou/whats-up-docker#37]
I get this email for WUD running `linux/amd64`:
```
Registry: hub

RegistryUrl: https://registry-1.docker.io/v2

Image: fmartinou/whats-up-docker

Current tag: 4.0.2

Current digest: sha256:359fdef4c39f86c3971ed59dabc14a3cb8ad8cd97261852023b9d21b1446d4d9

Result tag: undefined

Result digest: sha256:c11a1142d2195e92cf2f42a6b1210a920234b070c4302b2b26fc12fac2fd64ba
```

And this email for WUD running `linux/arm/v7`:
```
Registry: hub

RegistryUrl: https://registry-1.docker.io/v2

Image: fmartinou/whats-up-docker

Current tag: 4.0.2

Current digest: sha256:d5206e8337ce736cac456daa56e564209d7497fa15fc6f08439dccc84e1da271

Result tag: undefined

Result digest: sha256:c11a1142d2195e92cf2f42a6b1210a920234b070c4302b2b26fc12fac2fd64ba
```

Both report the same ResultDigest, which is unexpected given different platforms.

**Comment by fmartinou** [comment]
Hi @rasmuslp,
I maybe have something working regarding multiarch images.
Could you give a try to fmartinou/whats-up-docker:fix__37 and tell me if it's working better on your raspberry pi?

**Comment by fmartinou** [comment]
It's now available in version `4.1.0`

**Comment by rasmuslp** [comment]
Hi @fmartinou 

I have deployed `4.1.1` on two host, and it now detects the correct digests for `linux/arm/v7` 🎉 

And thank you for this flag
> We suggest enabling `wud.watch.digest` only where it's convenient (e.g. on latest versions). 
>If you face quota related errors, consider slowing down the watcher rate by adjusting the WUD_WATCHER_{watcher_name}_CRON variable.

Handy for images where something changes, and the version number doesn't.

**Comment by fmartinou** [comment]
I'm glad to see that it fixed your issue! :)
