### ISSUE TITLE
Enhancement request: Add watcher name to web UI summary

### ISSUE THREAD

**Issue by KeithB** [fmartinou/whats-up-docker#370]
**Context**
I've been using WUD for a while and now have it comfortably tracking containers on a bunch of different hosts, combined with HA, nodered and a helper script it's doing a great job of controlled automated upgrades across multiple hosts based on groups (what is allowed to auto-update on minor, what can on patch, etc)

**Request**
The UI includes container name and versions on the summary page when condensed but it would be really useful to include the watcher name too. I appreciate it's still there if you click through a few expansions but for a summary glance that's not great.

**Comment by davidosomething** [comment]
2nd this, i have containers with same name across multiple docker hosts:
![image](https://github.com/user-attachments/assets/70160cf5-e203-4d36-8dcb-275340a95614)

would love another column for "watcher" name or docker hostname

**Comment by fmartinou** [comment]
Hi,

It will look like that:
![image](https://github.com/user-attachments/assets/10404637-911c-4408-baf5-e98ae44e4bbf)

**Comment by fmartinou** [comment]
Available in `6.6.0`

**Comment by KeithB** [comment]
Thank you!
