### ISSUE TITLE
Incorrect detection of new version

### ISSUE THREAD

**Issue by Manuki-San** [fmartinou/whats-up-docker#375]
WUD (version 6.3.0) detects that container based on image emby/embyserver can be updated from 4.9.0.12 to 4.9.0.9 (which is a lower version) despite the tag format being defined as ^\d+\.\d+\.\d+\.\d+$

![image](https://github.com/fmartinou/whats-up-docker/assets/49970628/46f1058f-51d1-4c7e-abce-ac84bfffcbe9)

I suspect that the comparison between the 2 versions is done lexicographically (the "1" of ".12" < ".9") instead of numerically as recommended by the tag format.

**Comment by fmartinou** [comment]
Hi,

This behavior is consistent with the [semver specification](https://semver.org/).
I.e. Numeric identifiers only exist for major, minor and patch.
The part at the right is considered as a "prerelease" or a "build"so it must be compared __lexically__.

Please notice that the __includeTags__ regex is just here to filter candidates; using `\d` doesn't play a role for the semver comparison/resolution.

I am sorry for you but the main issue there, is that Emby tags are not semver compliant ;)
You can try to discuss with the Emby dev team to see if they can make them compliant with the spec 🤷‍♂️

**Comment by Manuki-San** [comment]
thank you for the explanation
