### ISSUE TITLE
[Feature request] Disable/hide the “Delete” option in the frontend

### ISSUE THREAD

**Issue by okunze** [fmartinou/whats-up-docker#385]
**Describe the solution you'd like**
I would like to see an option to disable/hide the “Delete” option in the frontend.

Currently I put the frontend behind authenticatio so that nobody can make deletions.

If the “Delete” option could be hidden/disabled, I could make the WebUI freely visible.

Maybe something like this:

```
### WebUI

| Env var                    | Required | Description                                     | Supported values | Default value when missing |
| -------------------------- | -------- | ----------------------------------------------- | ---------------- | -------------------------- | 
| `WUD_WEBUI_DISABLE_DELETE` | No       | Disable "Delete" button for containers in WebUI | true / false     | false                      |
```

**Comment by fmartinou** [comment]
The new prop is `WUD_SERVER_FEATURE_DELETE`
([see doc here](https://fmartinou.github.io/whats-up-docker/#/configuration/server/))

Available from release `6.5.0`.
