### ISSUE TITLE
[Feature Request] Add link to new release notes too

### ISSUE THREAD

**Issue by tedstriker** [fmartinou/whats-up-docker#389]
It would be nice and safe a few clicks, if the `wud.link.template` would not only generate a link to the deployed versions release notes but also to the release notes of the to-be-installed versions as well (if there's a discrepancy between deployed and latest available verison).

e.g.
wud.link.template: https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}

could result in 

Link:
https://github.com/fmartinou/whats-up-docker/releases/tag/6.3.0 (deployed)
https://github.com/fmartinou/whats-up-docker/releases/tag/6.3.1 (latest release)

if a new release has been identified by wud

**Comment by fmartinou** [comment]
Hi,

The template is used to format links for both the current and the target versions:

```json
{
   "linkTemplate":"https://github.com/redis/redis/releases/tag/${major}.${minor}.${patch}", <-- link template
    ...,
   "updateAvailable":true,
   "updateKind":{
      "kind":"tag",
      "localValue":"7.2.4-alpine",
      "remoteValue":"7.2.5-alpine",
      "semverDiff":"patch"
   },
   "link":"https://github.com/redis/redis/releases/tag/7.2.4", <-- link to current version
   "result":{
      "tag":"7.2.5-alpine",
      "link":"https://github.com/redis/redis/releases/tag/7.2.5"  <-- link to target version
   }
}
```

And the links are displayed in WUD UI as well:
![image](https://github.com/fmartinou/whats-up-docker/assets/16061231/338582f0-7a45-46ba-93f1-3f7ee74ce48b)

![image](https://github.com/fmartinou/whats-up-docker/assets/16061231/ce1df7fd-bd6c-4098-bdfa-559655faaa78)

?

**Comment by tedstriker** [comment]
Oh my, I didn't realize it's on the update tab. Thanks for the clarification.
