### ISSUE TITLE
[Feature request] Add a new filter in the WebUI for update type

### ISSUE THREAD

**Issue by ngosang** [fmartinou/whats-up-docker#394]
I would like to have a combo/filter to filter the updates by version type. For example: Major, Minor or Patch version.
I apply "path" versions frequently for security and bug fixing. Having a way to filter will help me a bit. You already are displaying this information in the color of the version.

**Comment by fmartinou** [comment]
![image](https://github.com/user-attachments/assets/50f43eab-817a-40b4-a8d1-e462ca5c299f)

**Comment by fmartinou** [comment]
Now available from `6.5.0`

**Comment by ngosang** [comment]
@fmartinou Thank you very much. I really appreciate this. :heart:
