### ISSUE TITLE
Feature request: check dockerhub updates via mirror

### ISSUE THREAD

**Issue by jehy** [fmartinou/whats-up-docker#396]
Hi! Is it possible to implement checking of dockerhup updates via mirror? For example, via google mirror mirror.gcr.io ?

**Comment by fmartinou** [comment]
Hi,

Won't mirror.gcr.io shut down?

https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

Besides, some [other registries](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/) are already implemented.

If some are missing, I could add them.

Also to be noticed: you can configure a [custom registry](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/custom/) that can also work (depending on how "standard" the registry is).

**Comment by jehy** [comment]
Oh. I just had to specify image via gcr, not by docker hub, and it really works out if the box. That's great!

I support that using mirrors from docker daemon is not really necessary then :)
