### ISSUE TITLE
Help me understand the concept of the application

### ISSUE THREAD

**Issue by info-path** [fmartinou/whats-up-docker#397]
Apparently, I did not understand how the application works. In general, I understand the term TRIGGER as an initiator of an action, but does this application use it directly as the action?

Let me explain my situation:

- The WUD GUI reports that 12 updates available from 23 containers.
- CRON is set to every hour `0 * * * *`
- TRIGGER is set as WUD_TRIGGER_SMTP_GMAIL ...
- I started the application at 01:00
- I did not add the label 'WUD...' to any container

And now, what I don't understand:

1) How do I test without cron that I have configured SMTP correctly? No manual trigger?
2) In the GUI, I cannot manually update any container?
3) Today I received only three notifications at 13:00, 16:00, 18:00 (strange times) that an update is available for a single container. Why only a single container when there are 12 in total? And why exactly this specific one?
4) There was no update of the notified container

In general, I assumed that the application would check for available updates. I am not a fan of automatic updates; I like to decide myself which container to update. I assumed that I would receive a notification and I would personally decide which container to update.

I noticed the integration into Home Assistant. It would be great to display a card with available updates where I can define a trigger for each of them, which will initiate the actual event and thus update the container.

Did I misunderstand the whole concept of WUD?

**Comment by fmartinou** [comment]
Hello,

`TRIGGER` here actually means "performing an action".

Actions can take various forms:
- sending notifications (mail, sms...)
- sending events (mqtt message, amqp message, http request...)
- replacing the current container by the new version
- etc

> How do I test without cron that I have configured SMTP correctly? No manual trigger?

There is no manual trigger, right.
You can, though, run from the UI on-demand tasks without having to wait for the CRON schedule to trigger

![image](https://github.com/fmartinou/whats-up-docker/assets/16061231/fc8b5729-99d1-4676-b44c-8fdeb781da9f)

> In the GUI, I cannot manually update any container?

If you want to update a container, you need to configure the [Docker trigger](https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/docker/) (but it means that updates will be performed automatically).

> Today I received only three notifications at 13:00, 16:00, 18:00 (strange times) that an update is available for a single container. Why only a single container when there are 12 in total? And why exactly this specific one?

By default, the CRON run every hour at 00. If for some containers, a greater version is found on the registry, you'll get notifications for them.

Next executions wont notify you over and over (unless the version on the registry has changed meanwhile)

> In general, I assumed that the application would check for available updates. I am not a fan of automatic updates; I like to decide myself which container to update. I assumed that I would receive a notification and I would personally decide which container to update.

That's the main purpose of this tool.


> I noticed the integration into Home Assistant. It would be great to display a card with available updates where I can define a trigger for each of them, which will initiate the actual event and thus update the container.

Integrating the possibility to update a container from HA is a feature requested from a long time; I just don't have the time right now to implement ;)

I hope I have answered your questions.

**Comment by info-path** [comment]
Thanks a lot for the comprehensive answer. The 'Watch now' button didn't work for me, but I found that the problem was the rate limit on the docker hub - I sent a lot of queries to the docker hub during testing.

I like this app. And I think full integration into HA would suit it well :) 

Thanks for your work!

**Comment by fmartinou** [comment]
Thank you for your interest 👍 .

> I think full integration into HA would suit it well :)

Without any doubt 😃 .
