### ISSUE TITLE
The Latest Docker image fmartinou/whats-up-docker:6.4.1 wipes out several registries

### ISSUE THREAD

**Issue by boozeman** [fmartinou/whats-up-docker#398]
Hi,

When pulling the 6.4.1, it wipes out at least Ghcr and Lscr registry's on registries.

It Can be reproduce just pulling the 6.4.1 and then go back to 6.4.0

**Comment by Monoboy4ik** [comment]
[GHCR] - Bring back username because needed for image pulling - release notes

- WUD_REGISTRY_GHCR_USERNAME=****
- WUD_REGISTRY_GHCR_TOKEN=*****

**Comment by boozeman** [comment]
> [GHCR] - Bring back username because needed for image pulling - release notes
> 
> * WUD_REGISTRY_GHCR_USERNAME=****
> * WUD_REGISTRY_GHCR_TOKEN=*****

That hit the spot! My bad!
