### ISSUE TITLE
Feature suggestion: Run now / refresh for updating Watchers

### ISSUE THREAD

**Issue by rasmuslp** [fmartinou/whats-up-docker#40]
On my hosts, I have configured `WUD_WATCHER_local_CRON: '0 * * * *'`. This means that WUD will refresh its knowledge of Images at that CRON, at the `local` Docker, passed with volume mounted Docker socket `'/var/run/docker.sock:/var/run/docker.sock'`.

Having an 'Refresh' / 'Watch now' button, to get the state updated - at will - would be very convenient.

When I update containers, managed by Ansible, I like to verify that I'm all up to date by checking WUD. However I still see old versions listed for Images. Right now I simply restart the WUD container to see WUD detect the correct versions of running Images.

**Comment by fmartinou** [comment]
Hi,

It's currently possible to refresh individual images from the UI/API:
- [UI](https://fmartinou.github.io/whats-up-docker/#/ui/images)
- [API](https://fmartinou.github.io/whats-up-docker/#/api/image/watch-image)

Would you like a similar feature but for all the images at once (eg a "Watch all now" button)?

**Comment by fmartinou** [comment]
Hi @rasmuslp ,
This is now implemented (API and UI).
![image](https://user-images.githubusercontent.com/16061231/120490237-86ecd980-c3b8-11eb-8f6c-7bd0b7b9ca72.png)

You can try it using `fmartinou/whats-up-docker:develop`.

If it's ok for you, then it will be included in the next release of WUD.

**Comment by fmartinou** [comment]
It's now available in version 4.1.0
