### ISSUE TITLE
Feature Request: Display the watcher as a column in the Containers View in the Web UI

### ISSUE THREAD

**Issue by Tuxdude** [fmartinou/whats-up-docker#423]
I am loving WUD so far and it has been reliable for me. I monitor six different docker hosts using a single instance of WUD, with my watchers on my WUD instance set up to connect with the docker daemon on these hosts over the Docker TLS socket. I run the same container name across multiple hosts for the purpose of redundancy in my network.

Right now when the Containers view shows all the containers with updates available, it displays all of my containers across different watchers together as shown below. Only on expanding each of them, I will be able to identify which docker host (aka watcher) this container belongs to.

It will be useful if WUD displays the watcher name directly within the row without having to expand it. Of course I can filter on the Watcher, but given the number of watchers (aka docker hosts I have) it's not a straightforward thing. Having this info directly in the row would be easier. Besides, there is plenty of free space on the row to display this information. Please see the attached screenshot which shows this better. Thanks!

![Screenshot from 2024-08-17 17-51-53](https://github.com/user-attachments/assets/b99ac063-c03f-43fd-b9aa-29b46100f47a)

**Comment by fmartinou** [comment]
#370 duplicate; it's been released in `6.6.0` 😃
