### ISSUE TITLE
Error appearing when browsing to WUD

### ISSUE THREAD

**Issue by Retract1822** [fmartinou/whats-up-docker#438]
When browsing to the WUD main page a pop up appears stating:

`Error when trying to get app version (JSON.parse: unexpected character at line 1 column 1 of the JSON data)` 

Image Tag: `ghcr.io/fmartinou/whats-up-docker:latest`

Image ID: `sha256:00ba23821eec26904be70ea29bbb9061fa9e2445aed9e4bd134131add635180b`

![error_screenshot](https://github.com/user-attachments/assets/7229485f-83e9-47aa-92a1-75c2e5c6d135)

**Comment by norfair00** [comment]
I have same issus

**Comment by fmartinou** [comment]
Hi,

I cannot reproduce the issue (tried with anonymous access and basic auth).

Can you share your config please? To understand what can cause a side-effect.

**Comment by fmartinou** [comment]
This API route is indeed protected by the authentication layer.

I don't understand why in certain circumstances, it's called from the UI whereas the login has not been made 🤔 .
As a fix, I open this particular route for anonymous access (it doesn't expose any sensitive data).

**Comment by fmartinou** [comment]
Available in `6.6.0`

**Comment by cryptogeek13** [comment]
Sorry to necro this, but I have the same issue on the latest release (8.0.1). For every line of `JSON.parse: unexpected character at line 1 column 1 of the JSON data` there is a failed call to `/triggers`. Note, that not all of them are failing though. I'm also behind a reverse proxy (traefik). Clearing browser cache does not change anything.

![Image](https://github.com/user-attachments/assets/993c9f95-16e2-42b2-bb03-ddadee73def0)
