### ISSUE TITLE
Docker image names ellipsed on mobile

### ISSUE THREAD

**Issue by bramvdzee** [fmartinou/whats-up-docker#444]
The 6.6.0 update makes it so that docker image names cannot be viewed on all viewports.

Is it possible to make the name configurable?

![IMG_0050](https://github.com/user-attachments/assets/f6ba5853-0a85-4787-a231-bd58ceae7ec1)

**Comment by fmartinou** [comment]
I propose to remove icons and registry details from the title to save some space.

**Desktop view:**
![image](https://github.com/user-attachments/assets/661ec9b7-6b75-4a3c-94f0-cf9c9112c564)

**Mobile view**
![image](https://github.com/user-attachments/assets/aff984c2-f1e5-4262-ab97-a7a74cc07678)

**Comment by fmartinou** [comment]
Fixed in `6.6.1`
