### ISSUE TITLE
WUD 5.0 not triggering update for container using latest tag

### ISSUE THREAD

**Issue by gmarlow** [fmartinou/whats-up-docker#45]
deleted by user.

**Comment by gmarlow** [comment]
I think my initial error was due to a breaking change in 5.0

**Comment by fmartinou** [comment]
Should be related to the fact that tracking digest is now disabled by default.

Adding `wud.watch.digest=true` labels on the containers should fix the issue [as mentioned here](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/docker/?id=supported-labels).
