### ISSUE TITLE
[Feature Request] Add direct link to the container registry page on the image tab

### ISSUE THREAD

**Issue by mbjurstrom** [fmartinou/whats-up-docker#455]
Hello,
Found out about this great piece of software last week and is loving it so far. I really prefer it over watch dog that I used before.
One thing that I would like to request (if possible) is to have a direct link to the corresponding container registry page on the image tab for each container.  For example https://hub.docker.com/r/fmartinou/whats-up-docker for whats-up-docker container. 
Either make the name, or registry a clickable link or add another entry to the image tab.  

The reason for this is to be able to read the updated documentation for the container and see what have changed before updating the containers. Now I need to actively find the correct page manually each time.

**Comment by fmartinou** [comment]
Hello,

Thank you for supporting wud 🙏  .

I have a good news for you; this feature already exists for a while 😄 

You can put a label `wud.link.template` on your container and `wud` will use it to render a browsable link from the UI.
(you can find some detail [here in the documentation](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels)).

Even better, this is a template so you can define placeholders for version digits that will be replaced at runtime; that allows to directly point to the specific changelog of the version you can update to.

For example
```yaml
version: '3'

services:

  mariadb:
    image: mariadb:10.6.4
    labels:
      - wud.link.template=https://mariadb.com/kb/en/mariadb-$${major}$${minor}$${patch}-changelog
```

And at runtime, it will point to `https://mariadb.com/kb/en/mariadb-1064-changelog`

=> [You can also find here some realistic example](https://fmartinou.github.io/whats-up-docker/#/configuration/?id=complete-examples)

Enjoy! 🤘

**Comment by mbjurstrom** [comment]
Wow thanks I must have completely missed that in the documentation. That is perfect thank you.
