### ISSUE TITLE
Run as limited user

### ISSUE THREAD

**Issue by dragetd** [fmartinou/whats-up-docker#5]
While having the docker socket in the application basically already forces the security to low barrier, it would be still nice of the application ran as a limited user. 

To use the socket, the app needs write support to the socket - and thus could break out of the container and take over the host. The only solution I know so far is docker-proxy, which is out of scope of this project. But I think it is good practice to still run as a limited user and not root.

**Comment by fmartinou** [comment]
Hi,

Thank you for the suggestion.

Passing the user when running the container is not enough?
Something like:
```
docker run --user 1000:999 ...
```
(where the group id would match the `Docker` group id on the host)

**Comment by dragetd** [comment]
Good question. I never found a sound answer to what the good practice is here.

I personally like your suggestion - but often I have been told by docker-using people, that 'good containers' should not default to to run as root.

I do not know what the good practice is here. Maybe the scope of this issue could be to add a note to the README about 'If you want to run it as a limited user…' ? Don't know, need to think about this.

**Comment by LeonardMeyer** [comment]
@fmartinou I have a similar issue where WUD is writing his `wud.json` as `root`, which means tools like Duplicati or Duplicacy, which containers actually allow to set UID/GID, cannot restore the file for example. The `--user 1000:999` thing is alright, except when you use a docker compose file, then it gets [annoying](https://stackoverflow.com/questions/56844746/how-to-set-uid-and-gid-in-docker-compose). Maybe allow for setting it but check that the provided user belongs to docker group or something ? (which I assume you need).

**Comment by fmartinou** [comment]
> The --user 1000:999 thing is alright, except when you use a docker compose file, then it gets [annoying](https://stackoverflow.com/questions/56844746/how-to-set-uid-and-gid-in-docker-compose).

I don't get the real issue; is that only because you don't want to write hard-coded UID/GID values in your docker-compose.yml file?
If so, you just have to export UID and GID env vars (in your .bashrc or somewhere else...) and use theses variables in your compose file.
Am I missing something?

**Comment by LeonardMeyer** [comment]
@fmartinou Nevermind, I tried hardcoding it in the compose file but for some reason it did not work at the time, now it does ! I must've messed up previously.  As long as the limited user belongs to the docker group it should be fine right for WUD ?

**Comment by fmartinou** [comment]
> As long as the limited user belongs to the docker group it should be fine right for WUD ?

Exactly.

**Comment by LeonardMeyer** [comment]
@fmartinou Well actually it does not work.

```
04:00:00.751  WARN whats-up-docker/watcher.docker.safeupdate: Error when trying to get the list of the containers to watch (connect EACCES /var/run/docker.sock)
```

The compose file is [here](https://github.com/LeonardMeyer/ansible-homemedia/blob/master/roles/compose/templates/docker-compose.yml.j2#L207). My user uid and gid are used and my owner is part the docker group.

```
user@machine:~$ id
uid=1000(user) gid=1000(user) groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd),998(docker)
```

These are the socket's permissions
```
srw-rw----  1 0 998    0 May 26 11:46 docker.sock
```

Same thing from inside the container. So I guess it's not as simple as that ?
