### ISSUE TITLE
MQTT Uri not recognized

### ISSUE THREAD

**Issue by ronnydahl** [fmartinou/whats-up-docker#50]
Hey, I'm getting an interesting error while trying to run MQTT trigger registration. When registering an MQTT trigger, I add the required (I think) environment variables. When specifying WUD_TRIGGER_MQTT_MOSQUITTO_URL, I get an error when reviewing the logs. Also, there is a horde of different warnings in the log, so I have probably F'ed something up. 

Here's the full log:
--
today at 10:22:57 AM [2021-07-14T08:22:57.930Z]  INFO: whats-up-docker/7 on 26395fd6a372: What's up Docker? is starting (version = 5.1.0)
today at 10:22:57 AM [2021-07-14T08:22:57.931Z]  INFO: whats-up-docker/7 on 26395fd6a372: Load DB (/store/wud.json)
today at 10:22:57 AM [2021-07-14T08:22:57.942Z]  INFO: whats-up-docker/7 on 26395fd6a372: Migrate data from version latest to version 5.1.0
today at 10:22:57 AM [2021-07-14T08:22:57.944Z]  INFO: whats-up-docker/7 on 26395fd6a372: Init Prometheus module
today at 10:22:57 AM [2021-07-14T08:22:57.985Z]  INFO: whats-up-docker/7 on 26395fd6a372: Register all components of kind triggers for provider mqtt
**today at 10:22:58 AM [2021-07-14T08:22:58.076Z]  WARN: whats-up-docker/7 on 26395fd6a372: Some triggers failed to register (Error when registering component mqtt ("url" must be a valid uri with a scheme matching the mqtt|mqtts|tcp|tls|ws|wss pattern))**
today at 10:22:58 AM [2021-07-14T08:22:58.225Z]  INFO: whats-up-docker/7 on 26395fd6a372: Register component hub of type hub with configuration {"auth":"c**************************************************************="}
today at 10:22:58 AM [2021-07-14T08:22:58.709Z]  INFO: whats-up-docker/7 on 26395fd6a372: Register component local of type docker with configuration {"host":"socket-proxy","socket":"/var/run/docker.sock","port":2375,"cron":"0 * * * *","watchbydefault":true,"watchall":false}
today at 10:22:58 AM [2021-07-14T08:22:58.710Z]  INFO: whats-up-docker/7 on 26395fd6a372: Schedule runner (0 * * * *)
today at 10:22:58 AM [2021-07-14T08:22:58.728Z]  INFO: whats-up-docker/7 on 26395fd6a372: HTTP API exposed on port 3000
today at 10:22:58 AM (node:7) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
today at 10:22:58 AM (Use `node --trace-deprecation ...` to show where the warning was created)
today at 10:22:59 AM [2021-07-14T08:22:59.762Z]  WARN: whats-up-docker/7 on 26395fd6a372: c2c1cc5f6af863f991271736dad0fd5388c26594976602979093b020e5c4f0bc - No Registry Provider found
today at 10:22:59 AM [2021-07-14T08:22:59.766Z]  WARN: whats-up-docker/7 on 26395fd6a372: c69162f2d653f63b5314c43a56b68e8c5613bf43f39f634f7e8dbb20d14ea017 - No Registry Provider found
today at 10:22:59 AM [2021-07-14T08:22:59.769Z]  WARN: whats-up-docker/7 on 26395fd6a372: a35cb4b6ef229e094945938dd802c4f72a90eb5d79ecb874e9ccf011af05b871 - No Registry Provider found
today at 10:22:59 AM [2021-07-14T08:22:59.774Z]  WARN: whats-up-docker/7 on 26395fd6a372: d23e2c1f66573e15e0e945405ad18fd5f935a5a641019be2997fa60f65923a96 - No Registry Provider found
today at 10:22:59 AM [2021-07-14T08:22:59.776Z]  WARN: whats-up-docker/7 on 26395fd6a372: 7f986f0a79fb43c5301fde14da627f7effd14c7b43ca20f0e91ae0ac2e703026 - No Registry Provider found
today at 10:22:59 AM [2021-07-14T08:22:59.803Z]  WARN: whats-up-docker/7 on 26395fd6a372: 7f986f0a79fb43c5301fde14da627f7effd14c7b43ca20f0e91ae0ac2e703026 - Error when trying to find new version (Unsupported Registry unknown)
today at 10:22:59 AM [2021-07-14T08:22:59.806Z]  WARN: whats-up-docker/7 on 26395fd6a372: a35cb4b6ef229e094945938dd802c4f72a90eb5d79ecb874e9ccf011af05b871 - Error when trying to find new version (Unsupported Registry unknown)
today at 10:22:59 AM [2021-07-14T08:22:59.807Z]  WARN: whats-up-docker/7 on 26395fd6a372: c69162f2d653f63b5314c43a56b68e8c5613bf43f39f634f7e8dbb20d14ea017 - Error when trying to find new version (Unsupported Registry unknown)
today at 10:22:59 AM [2021-07-14T08:22:59.808Z]  WARN: whats-up-docker/7 on 26395fd6a372: d23e2c1f66573e15e0e945405ad18fd5f935a5a641019be2997fa60f65923a96 - Error when trying to find new version (Unsupported Registry unknown)
today at 10:22:59 AM [2021-07-14T08:22:59.810Z]  WARN: whats-up-docker/7 on 26395fd6a372: c2c1cc5f6af863f991271736dad0fd5388c26594976602979093b020e5c4f0bc - Error when trying to find new version (Unsupported Registry unknown)
today at 10:22:59 AM [2021-07-14T08:22:59.815Z]  WARN: whats-up-docker/7 on 26395fd6a372: Error when processing images (Cannot read property 'tag' of undefined)
--

Relevant config from docker-compose:
---
  wud:
    container_name: wud
    image: fmartinou/whats-up-docker:5.1.0
    restart: unless-stopped
    networks:
      - socket_proxy
    environment:
      - WUD_WATCHER_LOCAL_HOST=socket-proxy
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL="mqtt://192.168.1.218:1883"
      - WUD_TRIGGER_MQTT_MOSQUITTO_USER="some-user"
      - WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD="some-password"
      - WUD_TRIGGER_MQTT_MOSQUITTO_TOPIC="wud/image"
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED="true"
      - WUD_REGISTRY_HUB_AUTH="some-token"
    volumes:
      - $DOCKERDIR/appdata/wdu/store:/store
---

What am I doing wrong here?

**Comment by fmartinou** [comment]
Hi,

I think that your issues are mainly caused by misplaced quotes around the env vars in your docker-compose.yml.

([see details here](https://github.com/docker/compose/issues/2854))

For example, replace:
 - WUD_TRIGGER_MQTT_MOSQUITTO_URL="mqtt://192.168.1.218:1883"

With
- WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://192.168.1.218:1883
Or
- "WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://192.168.1.218:1883"

(or use the dict notation instead of the array notation).

**Comment by ronnydahl** [comment]
Thanks Manfred. That was a stupid mistake on my end :) It works as intended now.
