### ISSUE TITLE
Usage of wud.watch

### ISSUE THREAD

**Issue by oliroe** [fmartinou/whats-up-docker#55]
For my usage I'd like WUD to check all containers apart from those I specifically exclude. I've tried adding wud.watch=false to the few I don't want to monitor but it doesn't do anything

Am I right in thinking the usage of wud.watch is in conjunction with WUD_WATCHER_{watcher_name}_WATCHBYDEFAULT=true
i.e. you have to set none to watch and include the ones you do with wud.watch=true

Is it possible to check all and just exclude a few?

**Comment by fmartinou** [comment]
Hi @oliroe ,
Your assumption is correct; currently you can:
- either watch all containers without exclusions
- or watch only the containers labeled with `wud.watch=true`.

The feature you request is easy to implement; I add it to my TODO list and I keep you informed once it's done.

**Comment by oliroe** [comment]
Many thanks, love the app by the way

Any chance of slimming down the gui, there's quite a lot of wasted real estate?

![image](https://user-images.githubusercontent.com/4500141/127477090-44dd1f13-e707-444e-a221-b0e28d4241ad.png)

**Comment by fmartinou** [comment]
Do you have any UX suggestions?
Or decreasing the font-size & margins maybe?
(I'm not a talented web designer LOL...)

Is it for a desktop or a smartphone usage?

**Comment by oliroe** [comment]
Not a problem, I'm only nit-picking. My usage is desktop only

If you take Portainer as an example, a lot more information can be seen without it being cramped
Just a suggestion, feel free to tell me to disappear :)

![image](https://user-images.githubusercontent.com/4500141/127484392-5f5cb76b-83c6-473a-9825-1d1335ea9be9.png)

**Comment by fmartinou** [comment]
LOL :)

Thanks for the suggestion; I'll think about it.

**Comment by fmartinou** [comment]
Hi @oliroe ,

May you test the version `fmartinou/whats-up-docker:feature__55`, please?
As requested, it should allow you to watch all your containers except the ones you explicitely excluded.

[It's documented here](https://github.com/fmartinou/whats-up-docker/blob/feature/%2355/docs/configuration/watchers/docker/README.md#exclude-specific-containers-to-watch).

If it's ok for you, then the feature will be available in the next release.

**Comment by oliroe** [comment]
Awesome, thanks for doing this

The link to the docs 404s by the way

**Comment by fmartinou** [comment]
Oops... The broken link is fixed.

**Comment by oliroe** [comment]
Looks good to me
Ran it with WUD_WATCHER_LOCAL_WATCHBYDEFAULT=true which pulled back the status of all my containers. I then used the label wud.watch=false on a couple of them and refreshed. The status of these weren't shown
Good work

**Comment by fmartinou** [comment]
@oliroe 

Great; I merge the changes.

By the way, I can see on your Portainer screenshot that you're also using Diun; what's your feedback on wud versus diun?

**Comment by oliroe** [comment]
@fmartinou 
I'm currently running both to see which I prefer and there are pros and cons for each. These are purely my own thoughts so don't take offence 

I'm a GUI man myself so love the fact you offer it. If it were me I'd set a volume for the config of WUD rather than just using environments and labels, to me it defeats the purpose of a GUI if it's all pretty much read only. Would it be possible to select which containers are tracked through the GUI rather than using labels on each container as an example

I prefer the fact WUD looks for an update based on the container you are running whereas Diun ignores this and just checks whether the image has changed at source. Diun's approach means I need to check the recent notifications to see if the images have been updated whereas with WUD I can just check the GUI to see which is out of date.

I prefer the notification sent by Diun (which can be customised for both the header and the content) as it's more concise and also offers a link.

Both are rock solid and do the job nicely, my ideal would probably be somewhere in between the two.

Good work

![Screenshot_20210803-110929](https://user-images.githubusercontent.com/4500141/127998951-e5975245-8485-4240-bf97-f4918e6b0716.png)
![Screenshot_20210803-111006](https://user-images.githubusercontent.com/4500141/127998956-a1d9696b-fd5f-4063-8d06-9c64ca959f4e.png)

**Comment by fmartinou** [comment]
Thank you for taking the time to write such a detailed answer; it gives me valuable insights about user expectations! :)

#### Regarding the UI
I've never considered the UI as a key feature of WUD, more likely a "nice-to-have" feature to give more readibility on what's going on.
Now that the UI is quite clean, I can understand that it's frutrasting because read-only.

The reason why I've focused the tool on env vars & labels instead of human clicks is because, with that system, the whole configuration can be described in a single docker-compose.yml file that you can easily track on Git.
And so you get for free:
- immutability
- history
- audit
- backup
- rollback
- ...

If I offer a way to configure WUD from the UI, users'll have to take care themselves of keeping safe wud config as for any regular Database.

I need to think about it and see if something smart could be implemented 🤔 .

#### Regarding Notifications
I agree with you; wud notification layout is very basic (euphemism 😂 ).
Are you using the Pushover integration?
It shouldn't be a big deal to improve them to get a more polished display; I add the improvement to my todo list.

Thanks again for your support 👍 .

**Comment by oliroe** [comment]
It's a pleasure

I see your point on using docker-compose for settings, maybe it's just personal taste that I prefer docker-compose start the app and configuration held in volumes. If I look at what I use (Portainer, TTRSS, *arr, NextPVR, Wordpress etc) the vast majority of the settings are held within the volume for the app so it's just what I'm used to. Completely appreciate for a utility like WUD that it may be preferable to keep everything within docker-compose.

Thanks again

**Comment by fmartinou** [comment]
Excluding containers using `wud.watch` has been added to version [`5.2.0`](https://fmartinou.github.io/whats-up-docker/#/changelog/?id=_520)
