### ISSUE TITLE
Clicking 'Refresh All' doesn't change colour of the tag to orange

### ISSUE THREAD

**Issue by oliroe** [fmartinou/whats-up-docker#57]
Hi

Clicking the refresh all button doesn't change the tag to orange of show the sha when an update is available.
I've just clicked it and received a notification to say there's an update, only a refresh of the browser shows the update on the GUI. It looks like refresh all also needs to refresh the list of containers

Thanks

Further to this, this is the behaviour I'm seeing.....

If there is an update available clicking refresh all doesn't turn the tag to orange but refresh the specific container does
If the GUI shows the container as orange (update available) and the container is updated then refresh all has the expected action of changing the tag back to green.

It appears refresh all is not the same as clicking refresh on the individual containers

**Comment by fmartinou** [comment]
Hi,

UI has changed a lot since August; could you check if it's still occuring?
Thanks

**Comment by fmartinou** [comment]
Finally observed this issue with my own eyes 😂 
I'm gonna fix it.

**Comment by fmartinou** [comment]
Fixed with `5.7.2`
