### ISSUE TITLE
Error when running check

### ISSUE THREAD

**Issue by oliroe** [fmartinou/whats-up-docker#62]
Hi

Is anyone else seeing errors like this occasionally? Happen for all containers in that schedule

![image](https://user-images.githubusercontent.com/4500141/129873492-a9aa073d-33a3-45cd-a4ce-b9a5c3518176.png)

Currently running a check every 6 hours and I'd say 1 in 4 seem to be failing with the above errors

**Comment by fmartinou** [comment]
Hi,

Personnally, I've never experienced this one.

`EAI_AGAIN` means there was a DNS resolution error (while trying to resolve auth.docker.io associated ip addresses).

Are you using a custom DNS forwarder/resolver on your end? (dnsmasq/pihole, bind...) ?

**Comment by oliroe** [comment]
Nothing unusual at my end from a DNS point of view, weird how it only happens occasionally.
Would you mind leaving this open for a bit to see if anyone else has similar issues?

**Comment by fmartinou** [comment]
Sure!

**Comment by oliroe** [comment]
Thanks
I don't suppose this means anything to you?

![image](https://user-images.githubusercontent.com/4500141/129909120-9425d172-10dc-4198-a947-c590a91fccea.png)

I've restarted the container to see whether that stops it happening again

**Comment by oliroe** [comment]
Hmmm, looks like I'm only seeing these errors in the run that happens at midnight. Going to monitor it for a few more days and if it's the case change the cron job (currently 0 */6 * * *) to not start on the hour

**Comment by oliroe** [comment]
I haven't seen the issue since changing the Cron job to 10 */6 * * *, guessing other processes must be happening at midnight. Looks like a local issue rather than anything wrong with wud.
