### ISSUE TITLE
Publish Container Operational State over MQTT

### ISSUE THREAD

**Issue by jeremywillans** [fmartinou/whats-up-docker#68]
Is it possible to publish the containers operational state as an additional attribute over MQTT?

This will be useful as an additional metric in HA for entity filtering

**Comment by fmartinou** [comment]
Just to be clear; the state (running, stopped...) will just reflet the state found when the watcher was last executed.
It won't reflect the current state of the container.
Is that ok?

**Comment by fmartinou** [comment]
Can you give it a try?
`fmartinou/whats-up-docker:feature__68`

(please remove WUD state before [if mounted as persistent volume](https://fmartinou.github.io/whats-up-docker/#/configuration/storage/) or you'll get "unknown" states)

**Comment by jeremywillans** [comment]
Ok, so I can see the status in WUD, but the attribute does not appear to be getting passed through to MQTT

**Comment by jeremywillans** [comment]
Raised #70 to fix, I've tested and confirmed it correctly shows when named status 👍 

![Cursor_and_Developer_Tools_-_Home_Assistant](https://user-images.githubusercontent.com/31495062/134443504-bcd63344-be4a-45b9-a592-c09daa1c6b4b.png)

**Comment by fmartinou** [comment]
> not appearing as an attribute in HA. I presume this is because "state" is reserved/used for the actual entity state

Yeah, bad luck 😄

**Comment by fmartinou** [comment]
Thank you very much for the PR!
Nice work! 👍 

In addition, I just changed in the same way the label on the UI (State -> Status).
[It's building on Travis right now...](https://app.travis-ci.com/github/fmartinou/whats-up-docker/builds/238329155)

**Comment by fmartinou** [comment]
Tested OK on my end.

The feature will temporary be available under the tag `develop` until the next release is pushed (should be a `5.7.0`).

**Comment by fmartinou** [comment]
Available in `5.7.0`
