### ISSUE TITLE
 UnhandledPromiseRejectionWarning after installation

### ISSUE THREAD

**Issue by kamad3** [fmartinou/whats-up-docker#7]
I really like your idea and would have liked to give it a try, but after running the container with the following command:

docker run -d --name=whats-up-docker -e WUD_WATCHER_DOCKER_LOCAL_CRON="0 3 * * 6" -e WUD_TRIGGER_SMTP_LOCAL_HOST=smtp.gmail.com -e WUD_TRIGGER_SMTP_LOCAL_PORT=465 -e WUD_TRIGGER_SMTP_LOCAL_USER=xxxx@gmail.com -e WUD_TRIGGER_SMTP_LOCAL_PASS=zzzz -e WUD_TRIGGER_SMTP_LOCAL_FROM=xxxx@gmail.com -e WUD_TRIGGER_SMTP_LOCAL_TO=yyyy@gmail.com --restart unless-stopped fmartinou/whats-up-docker

I received an exception. Could you please check it?

{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"What's up, docker? is starting","time":"2020-04-18T18:04:57.375Z","v":0}
{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"Init DB (/store/wud.json)","time":"2020-04-18T18:04:57.377Z","v":0}
{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"DB empty => Create DB Collections","time":"2020-04-18T18:04:57.379Z","v":0}
{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"Register all components for provider smtp","time":"2020-04-18T18:04:57.383Z","v":0}
{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"Register component Local of type Smtp with configuration {\"to\":\"yyyy@gmail.com\",\"host\":\"smtp.gmail.com\",\"user\":\"xxxx@gmail.com\",\"port\":\"465\",\"from\":\"xxxx@gmail.com\",\"pass\":\"zzzz\"}","time":"2020-04-18T18:04:57.460Z","v":0}
{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"Register all components for provider docker","time":"2020-04-18T18:04:57.469Z","v":0}
{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"Register component Local of type Docker with configuration {\"cron\":\"0 3 * * 6\"}","time":"2020-04-18T18:04:57.772Z","v":0}
{"name":"whats-up-doc","hostname":"1e13932c6c37","pid":1,"level":30,"msg":"Schedule runner (0 3 * * 6)","time":"2020-04-18T18:04:57.779Z","v":0}
(node:1) UnhandledPromiseRejectionWarning: Error: connect ENOENT /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fmartinou** [comment]
Hi,

Sorry, I missed your comment :(

You get this error because you forgot to mount the Docker socket inside the container:
`-v "/var/run/docker.sock:/var/run/docker.sock"`

You can take a look at the [Quickstart section](https://fmartinou.github.io/whats-up-docker/#/getting-started/quick-start
) in the documentation which mentions that.
