### ISSUE TITLE
WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED

### ISSUE THREAD

**Issue by TheDarthFather** [fmartinou/whats-up-docker#72]
Hello.
Thank you for this very nice initiative!

I just installed both mqtt and wud in 2 docker-containers next to my ha. 
All 3 ar in host network mode. 
**mqtt** seems to work fine .. i can send and receive test mesages in the HA integration
**wud** seems to work finish .. the gui is up ... no errors in log  .. I dont seen anything in mqtt tho ...
In mqtt I get this ... assuming from HA
1632861283: Received PUBLISH from 2uVM5AkIGltcfMibjyFN8S (d0, q0, r0, m0, 'homeassistant/status', ... (6 bytes))

I do have WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED as true but my HA instance did not autodetect wud as mentioned in the docs...

Is there anything I should look / test ?

**Comment by fmartinou** [comment]
Hi, welcome on board!

In the GUI of WUD, can you see your containers? (at least those 3 ones)?

Could you restart WUD with debug logs?
https://fmartinou.github.io/whats-up-docker/#/configuration/logs/

Then paste the logs here along with the configuration you set up?

Thanks.

**Comment by TheDarthFather** [comment]
Thnak you for the quick reply!
I enabled debug and cheked the log .... had an error regarding hass_ennabled not being a boolean.
In the Portainer Env setup, I had a space before "true"  for the hass_enabled :)

Works now! Thanks again!

**Comment by fmartinou** [comment]
Great!
Hope you enjoy it!
