### ISSUE TITLE
question/suggestion - docker label for changelog

### ISSUE THREAD

**Issue by ajgon** [fmartinou/whats-up-docker#73]
I was thinking about new docker label (similar to version regex), which contains link to changelog for given container. Then, when new image is available, web interface could display a link to this changelog (if present) so user could quickly check what changed, and what surprises to expect when they perform an update :)

What do you think?

**Comment by fmartinou** [comment]
Hi @ajgon ,

Guess what... it'as already implemented!

Exactly implemented as you was thinking about 😄 .

It's explained in the documentation:
- [`wud.link.template` label](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels)
- [and more precisely `Associate a link to the container version`](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=associate-a-link-to-the-container-version)

Then, in the UI, you can click the link to get you redirected to the changelog:
![image](https://user-images.githubusercontent.com/16061231/136035622-fdbbb018-3d65-471d-979f-d9b3a7683dca.png)

**Comment by fmartinou** [comment]
(it's available from version [`5.4.0`](https://fmartinou.github.io/whats-up-docker/#/changelog/?id=_540))

**Comment by ajgon** [comment]
It's awesome! How did I miss that? 😅 

Thanks! :)

**Comment by fmartinou** [comment]
I have to find a way to better highlight changes overtime... 🤔 .

By the way, I'm happy to see that you enjoy this feature too 👍
