### ISSUE TITLE
Another versioning problem / new label to solve it once for all?

### ISSUE THREAD

**Issue by ajgon** [fmartinou/whats-up-docker#75]
To be honest - this problem would return over and over again, since docker doesn't force any version tag format standard. I have an issue with searx container now - https://hub.docker.com/r/searx/searx/tags . It uses part of SHA hash of git commit at the end of their version tag, which obviously confuses WUD. Since hashes can't be ordered properly, WUD constantly is thinking that some new version is available.

I was thinking about introducing advanced `process-version` (or whatever name ;) ) label. This label would contain search & replace string in some standarized format, which would prepare version tag for further processing. So, using searx as example:

* searx tag: `1.0.0-267-3bcca43a`
* process-version label: `(^[0-9]\d*\.[0-9]\d*\.[0-9]\d*-[0-9]\d*)-?[0-9a-f]*$@$1`
    * I'm using `@` as search and replace separator, but this can be any char which can't be used in docker tag
    * `$1` is grouped match (again format doesn't matter as long as it's clear, `\1` would work as well, I think it's more what preference js regex libraries have)
* output searx "tag": `1.0.0-267`

And now this output tag can be used for further processing (match against `tagregex` label, check for new version etc.).

I realize this may overcomplicate some things (for example, checking for new version would also need to "preprocess" all the tags to check against), but at the end of the day, user can normalize versions to wud accepted format, which would also save you from constant struggle of supporting "yet another version format™" :)

What do you think?

**Comment by fmartinou** [comment]
Hi @ajgon ,

I get your point and I agree; providing a solution to map a weird tag to something more "semver compliant" before performing the comparison against values found on the registry could help a lot.

I don't know if you've already taken a look at the issue #56 opened by @thomazz-nl few months ago but is seems to me to be quite close.
The reason for the preprocessing is slighty different but in the end, the feature will probably be the same.

@thomazz-nl proposed a solution using simple Javascript Regex matching.

Applied to your example, it'd look like:
You set on your container the include tag `wud.tag.include=^\d+\.\d+\.\d+-\d+$`
Then at runtime, wud will perform something like
```javascript
let match = "1.0.0-267-3bcca43a".match(/^\d+\.\d+\.\d+-\d+$/); // match is an Array containing matches or null if there's no match.
let sanitizedTag = match ? match[0] : ""; // Ternary operator. If match is truthy, return the first match. If match is falsy, return an empty string.
console.log(sanitizedTag); // 1.0.0-267
```

This algo would run on both tags (the tag used by your container and all tags found on the registry)

Do you think it'd solve your issue as well?

**Comment by ajgon** [comment]
I assume, the `match` regex is not supposed to have `$` at the end - otherwise the code example wouldn't work :) But I see the point.

This makes sense, the only caveat I can think of, is when there are multiple tags including the same version. So for whatever reason, there will be tag `1.2.3-dev` and `1.2.3-prod`. Then this approach doesn't allow me to specify which tag I actually mean. Maybe let's use `match[1] || match[0]`? This would allow us to use brackets to extract version info if necessary. So for example:

```
let match = "1.2.3-dev".match(/^(\d+\.\d+\.\d+)-dev$/);
let sanitizedTag = match ? match[1] || match[0] : ""; // match[0] is fallback if there are no brackets in regex
console.log(sanitizedTag); // 1.2.3

let match = "1.2.3-staging".match(/^(\d+\.\d+\.\d+)-dev$/);
let sanitizedTag = match ? match[1] || match[0] : ""; // match[0] is fallback if there are no brackets in regex
console.log(sanitizedTag); // ""
```

Makes sense? :)

**Comment by ajgon** [comment]
Love it, and it works like a charm ❤️ 

I had to use single `$` instead of two, not sure why - but I'm using ansible to provision containers, maybe it does some magic under the hood...

**Comment by fmartinou** [comment]
Great!

The feature will be part of the next release.
