### ISSUE TITLE
Make it possible to hide the openid website.

### ISSUE THREAD

**Issue by Akruidenberg** [fmartinou/whats-up-docker#76]
Make ik possible to hide the login screen of WUT, even running with openid. The Openid provider already takes the login process.

Thanks in advance!

**Comment by Akruidenberg** [comment]
any progress @fmartinou Do you need more info?

**Comment by fmartinou** [comment]
I'm currently running out of time so I haven't started to work on it.
I 'll try to fix it using Auth0 because the setup is easier.
But if you can provide ready-to-go examples on how to integrate with authentik, I'll be able to directly test with the same IDP as you.

**Comment by fmartinou** [comment]
Hi,

I have a first implementation; could you give it a try?
`fmartinou/whats-up-docker:feature__76`

You just need to pass an extra env var indicating you want to skip the embedded login page and directly get redirected to the IDP.

`WUD_AUTH_OIDC_{auth_name}_REDIRECT=true`

[documentation draft](https://github.com/fmartinou/whats-up-docker/blob/feature/%2376/docs/configuration/authentications/oidc/README.md)

![authentik_auto_redirect](https://user-images.githubusercontent.com/16061231/140377711-898f07dd-420d-45f9-a954-28d773fd02e4.gif)

**Comment by Akruidenberg** [comment]
Thanks! Will try it out today

**Comment by Akruidenberg** [comment]
Tested. It's working perfectly! Thanks!

**Comment by fmartinou** [comment]
Available in version`5.11.0`
