### ISSUE TITLE
Add integration for quay.io registery

### ISSUE THREAD

**Issue by Akruidenberg** [fmartinou/whats-up-docker#78]
Some services like Prometheus are hosting package/images only on quay.io beside Docker Hub.
Maybe its an good idea to add support for this registry?
Prometheus is not available on GHCR at the moment, beside HUB.

**Comment by fmartinou** [comment]
I have a first version working with quay.io.

Could you please give it a try by testing the following wud image `fmartinou/whats-up-docker:feature__78`?

To enable the support of the quay registry, you just need to add the following env var to wud.
```
WUD_REGISTRY_QUAY=''
```
[here is the draft for the related documentation](https://github.com/fmartinou/whats-up-docker/blob/feature/%2378/docs/configuration/registries/quay/README.md)

**Comment by fmartinou** [comment]
Available in [`5.10.0`](https://fmartinou.github.io/whats-up-docker/#/changelog/?id=_5100)
