### ISSUE TITLE
Add lscr.io registry

### ISSUE THREAD

**Issue by oliroe** [fmartinou/whats-up-docker#79]
Hi

Any chance you could add the following registry?

[https://www.linuxserver.io/blog/wrap-up-warm-for-the-winter](url)

Thanks

**Comment by fmartinou** [comment]
Hi,

If lscr.io is implementing the standard docker-registry API V2, the support will be very easy. 🤞

I'll test it and I'll keep you informed.

**Comment by fmartinou** [comment]
Hi,

It was an easy one 😃 .

You can give it a try by testing `fmartinou/whats-up-docker:develop`

To enable the support of lscr.io, just set the following env var `WUD_REGISTRY_LSCR=''`
([documentation draft](https://github.com/fmartinou/whats-up-docker/blob/develop/docs/configuration/registries/lscr/README.md))

**Comment by oliroe** [comment]
Great news, been playing around with it a bit and now I've hit the rate limit 😊. I'll test it as soon as I'm able to refresh again

**Comment by oliroe** [comment]
Not sure whether it's something I've done wrong but I get this error

![image](https://user-images.githubusercontent.com/4500141/139700921-b6df3581-c5b9-49ef-a9cf-22ab6278c4d6.png)

![image](https://user-images.githubusercontent.com/4500141/139701024-90b6ac17-743e-4b5d-9157-5077eea9c87f.png)

**Comment by oliroe** [comment]
Ignore me, it's all ok. I mustn't have pulled the new develop image properly
Many thanks

**Comment by fmartinou** [comment]
Available in [`5.10.0`](https://fmartinou.github.io/whats-up-docker/#/changelog/?id=_5100)
