### ISSUE TITLE
Provide images to download WUD from ghcr.io

### ISSUE THREAD

**Issue by Akruidenberg** [fmartinou/whats-up-docker#81]
Some people like me prefer to download images from other registries. It would be nice to download WUD from ghcr.io instead of docker hub.

**Comment by fmartinou** [comment]
Done! 😃 

Starting from version `5.11.2`, wud images are pushed both to Docker Hub and Ghcr.

Example:
`docker pull ghcr.io/fmartinou/whats-up-docker`
