### ISSUE TITLE
LinuxServer.io calibre MANIFEST_INVALID

### ISSUE THREAD

**Issue by Depechie** [fmartinou/whats-up-docker#82]
I switched my calibre container to linuxserver.io and added WUD_REGISTRY_LSCR to the what's up docker environment variables. But I keep getting : `400 - {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}` as registry result in what's up docker.

Calibre-web does work and is also linked to linuxserver.io.

Any thoughts?

**Comment by fmartinou** [comment]
Hi,

I cannot reproduce your issue so far 🤔 .

Below the test I performed.

1. Deploy the following containers:
```yaml
version: '3'

services:
    lscr_calibre_latest:
      image:
        lscr.io/linuxserver/calibre-web
      container_name: lscr_calibre_latest

    lscr_calibre_semver:
      image:
        lscr.io/linuxserver/calibre-web:2021.10.31
      container_name: lscr_calibre_semver
      labels:
        - wud.tag.include=^\d+\.\d+\.\d+$$
```

2. Run WUD without any previous store files and with the following env vars:
- `WUD_REGISTRY_LSCR=""`
- `WUD_LOG_LEVEL="debug"`

The log:
```
INFO whats-up-docker: What's up Docker? is starting (version = dev)
...
INFO whats-up-docker/registry.lscr: Register registry with configuration {}
...
DEBUG whats-up-docker/watcher.docker.local: Start watching (container=local_lscr_calibre_semver)
DEBUG whats-up-docker/registry.lscr: lscr - Get linuxserver/calibre-web tags
DEBUG whats-up-docker/watcher.docker.local: Start watching (container=local_lscr_calibre_latest)
DEBUG whats-up-docker/registry.lscr: lscr - Get linuxserver/calibre-web:latest manifest
DEBUG whats-up-docker/registry.lscr: lscr - Get linuxserver/calibre-web:sha256:c8ee2c57c06a484afa085dbdd3a683c4c45586563f7afa6e61b43d5e6f47b5ca manifest
DEBUG whats-up-docker/registry.lscr: lscr - Get linuxserver/calibre-web tags
DEBUG whats-up-docker/watcher.docker.local: Container watched for the first time (container=local_lscr_calibre_semver)
DEBUG whats-up-docker/watcher.docker.local: Container watched for the first time (container=local_lscr_calibre_latest)
INFO whats-up-docker/watcher.docker.local: Cron finished (2 containers watched, 0 errors, 1 available updates)
```

The UI:
![image](https://user-images.githubusercontent.com/16061231/141751102-0765306e-f78f-47a4-906b-ac34f91afe56.png)

So everything is going well.

- Which version of wud are you running? (the latest `5.11.1`?)
- Did you try to remove first the wud.json file?

**Comment by Depechie** [comment]
So my deploy is only with portainer UI instead of docker compose, but that would not matter I guess.
Also running WUD 5.11.1 here.

What do you mean about removing the wud json file?

The log gives:

```
21:09:13.205  WARN whats-up-docker/watcher.docker.local: Error when processing (400 - {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}) (container=local_calibre)
21:09:13.206 DEBUG whats-up-docker/watcher.docker.local: 400 - {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]} (container=local_calibre)
    StatusCodeError: 400 - {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}
        at new StatusCodeError (/home/node/app/node_modules/request-promise-core/lib/errors.js:32:15)
        at Request.plumbing.callback (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
        at Request.RP$callback [as _callback] (/home/node/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at Request.self.callback (/home/node/app/node_modules/request/request.js:185:22)
        at Request.emit (node:events:390:28)
        at Request.<anonymous> (/home/node/app/node_modules/request/request.js:1154:10)
        at Request.emit (node:events:390:28)
        at IncomingMessage.<anonymous> (/home/node/app/node_modules/request/request.js:1076:12)
        at Object.onceWrapper (node:events:509:28)
        at IncomingMessage.emit (node:events:402:35)
        at endReadableNT (node:internal/streams/readable:1343:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
Only extra in my config is the `wud.watch.digest:true` label for calibre.

![Screenshot 2021-11-15 at 22 14 20](https://user-images.githubusercontent.com/351693/141854842-41705687-ea08-4d22-ab82-5f76a869d9ea.png)

**Comment by fmartinou** [comment]
I tested once again (including wud.watch.digest=true as well) and it's still working.

However I can see on your screenshot that the image digest is missing (but I don't know why); it's probably the reason why you get then an error when wud's trying to get the corresponding image digest on lscr.io.

Your situation
![image](https://user-images.githubusercontent.com/16061231/141952393-f7ef6b64-cb4f-41a1-9d2c-fc518ee81d12.png)

My situation
![image](https://user-images.githubusercontent.com/16061231/141952631-d0df37d5-222e-4262-a481-45a6c88aafd7.png)

> What do you mean about removing the wud json file?
WUD is persisting its state data on a JSON file.
- If you [mounted it into an host volume](https://fmartinou.github.io/whats-up-docker/#/configuration/storage/), then you should remove it and restart WUD to be sure to start over from an empty state.
- If you didn't mount it, then you should remove the existing WUD container and create a fresh new one to be sure to start over from an empty state.

(just to confirm that your issue is not caused by any existing state side effect)

**By the way: what architecture is your Calibre container running on? (`amd64` or something different like `arm/v7`, `arm64`...?)**

**Comment by Depechie** [comment]
Yeah, true about the digest... honestly no clue why it is not working either.
My architecture is : linux debian running on an intel nuc ( so x86-64 ).

About the WUD container, I also did do a recreate to be sure nothing remained.
And like I said the calibre-web one is working fine, so really weird :(

**Comment by fmartinou** [comment]
Weird...
Our platforms (x86-64) and our configurations seem pretty close 🤔 .

Could you perform those 2 tests, please:

1. Share the information about the docker version of your system
```bash
~$ docker version

Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community

 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

2. Force pull the calibre `latest` image to be sure to run the latest one (`docker pull lscr.io/linuxserver/calibre-web`) and test again

3. Change your calibre image to point to a semver version (e.g. `2021.11.16`) (and remove `wud.watch.digest=true` as well) to see if, as a workaround, this config could be working

```yaml
version: '3'

services:
    calibre:
      image:
        lscr.io/linuxserver/calibre-web:2021.11.16
      container_name: calibre
      labels:
        - wud.tag.include=^\d+\.\d+\.\d+$$
```

Thanks!

**Comment by Depechie** [comment]
![image](https://user-images.githubusercontent.com/351693/142759277-12f621bc-ed46-41a9-9ec3-1755899c6ff9.png)

I think it is fixed now!
Deleted all images and then did the manual `docker pull lscr.io/linuxserver/calibre` and recreated the container. ( thx for the tips )

**Comment by fmartinou** [comment]
The mystery remains but, anyway, I'm glad to know that it's finally working 🙂
