### ISSUE TITLE
Format of notification using Pushover

### ISSUE THREAD

**Issue by oliroe** [fmartinou/whats-up-docker#83]
Hi

This is a very anal request so feel free to close it the moment you've read it. This may well be just how Pushover displays the notification rather that anything at WUD's end but is it possible to remove the space in between the containers? When you have a number of updates they can't be seen on the notification

Thanks

![image](https://user-images.githubusercontent.com/4500141/141984316-f2a5f141-cc4c-4039-be06-1bea06eafc29.png)

![Screenshot_20211116-121802](https://user-images.githubusercontent.com/4500141/141984422-e9b80e99-18b8-4a5d-814d-657afd1fd43f.png)

**Comment by fmartinou** [comment]
I can understand :)

Could you try the version `fmartinou/whats-up-docker:fix__83` and confirm that the display is prettier?

**Comment by oliroe** [comment]
Spot on as always, looks good to me

![Screenshot_20211116-175851](https://user-images.githubusercontent.com/4500141/142040223-07eac753-7891-47b1-a298-80bfe2447aa1.png)

**Comment by fmartinou** [comment]
Great!

The improvement will be available in the next upcoming wud release.

**Comment by fmartinou** [comment]
Available in version `5.11.2`
