### ISSUE TITLE
stopped containers

### ISSUE THREAD

**Issue by April-ha** [fmartinou/whats-up-docker#85]
Hello
Would it be possible to see the state of the stopped containers as well?
Thank you for your excellent work

**Comment by fmartinou** [comment]
Hi,
You can already do it by configuring the Docker watcher:
https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/

with 'WUD_WATCHER_{watcher_name}_WATCHALL=true'

**Comment by April-ha** [comment]
Thank you very much, it works very well
