### ISSUE TITLE
docker-compose trigger option

### ISSUE THREAD

**Issue by ioull** [fmartinou/whats-up-docker#87]
It could be interressant to have an option to pull the new image but not doing the upgrade. So when we need to manually update, the image is ready and the docker-compose up is quickly available.

I don't like automatic update, and I don't like waiting ;-)

**Comment by fmartinou** [comment]
Brilliant! Love it!

It should not be too hard to implement...

**Comment by ioull** [comment]
I don't know enough your tool for the moment but perhaps it is not a docker-compose trigger option, but a general one as it can be used for docker trigger too  ?

**Comment by fmartinou** [comment]
Hi, 

I just added a new `dry-run` option for both `Docker` and `Docker-compose` triggers.
When enabled, the new image is pulled but the original container is not replaced by the new one (neither the Docker-compose is rewritten).

The env var to use is:
- `WUD_TRIGGER_DOCKER_{trigger_name}_DRYRUN` for the Docker trigger
- `WUD_TRIGGER_DOCKERCOMPOSE_{trigger_name}_DRYRUN` for the Docker-compose trigger

You should be able to test it on the dev version `fmartinou/whats-up-docker:feature__87`.
_(the feature will be part of the next release)_

Please let me know if it suits your need?
Thanks!

_In the mean time, I close the issue; feel free to tell me to reopen it if something goes wrong._

**Comment by fmartinou** [comment]
Available in `5.12.0`.

**Comment by ioull** [comment]
Thanks, Due to holidays, I just updated and wait for next container update to validate ;-)

**Comment by ioull** [comment]
2 updates today and it works fine !!! Very cool feature, no wait to redeploy !!! Thanks a lot ! 

For information instead of WUD_TRIGGER_DOCKERCOMPOSE_.... I use WUD_TRIGGER_DOCKER_... as I have seperate docker compose file for each service, so it is much easier for me to user docker trigger instead of docker_compose trigger!
