### ISSUE TITLE
How to configure docker-compose trigger 

### ISSUE THREAD

**Issue by Ikes72000** [fmartinou/whats-up-docker#90]
Hi,

I trie to use docker-compose trigger but it doesn't work, i don't  see it in the ui.

My docker-compose file:

`
version: '3'

services:
  whatsupdocker:
    image: fmartinou/whats-up-docker:5.11.2
    container_name: wud
    networks:
      - supervision
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data:/store
      - ${PWD}/docker-compose.yml:/wud/docker-compose.yml
    environment:
      - TZ=Europe/Paris
      - WUD_WATCHER_LOCAL_CRON=0 1 * * *
      - WUD_WATCHER_LOCAL_WATCHALL=false
      - WUD_TRIGGER_MQTT_MOSQUITTO_MODE=batch
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=tcp://xxx.xxx.xxx.xxx:1883
      #- WUD_TRIGGER_MQTT_MOSQUITTO_USER=XXXXXXXXXXXXX
      #- WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=XXXXXXXXXX
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_PREFIX=homeassistant
      - WUD_TRIGGER_DOCKERCOMPOSE_WUD_FILE=${PWD}/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_WUD_BACK=true
      - WUD_TRIGGER_DOCKERCOMPOSE_WUD_PRUNE=true
    labels:
      - wud.watch=true
      - wud.watch.digest=false
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}
    restart: unless-stopped

networks:
  supervision:
    external: true`

Container log:

```
19:25:28.876  INFO whats-up-docker/registry: Register all components of kind trigger for provider dockercompose
19:25:28.912  WARN whats-up-docker/registry: Some triggers failed to register (Error when registering component dockercompose ("back" is not allowed))
19:25:28.913  INFO whats-up-docker/registry: No Registry configured => Init a default one (Docker Hub with default options)
19:25:29.193  INFO whats-up-docker/registry.hub: Register registry with configuration {}
19:25:30.001  INFO whats-up-docker/watcher.docker.local: Register watcher with configuration {"cron":"0 1 * * *","watchall":false,"socket":"/var/run/docker.sock","port":2375,"watchbydefault":true}
19:25:30.003  INFO whats-up-docker/watcher.docker.local: Cron scheduled (0 1 * * *)
19:25:30.015  INFO whats-up-docker/registry: No authentication configured => Allow anonymous access
19:25:30.019  INFO whats-up-docker/authentication.anonymous.anonymous: Register authentication with configuration {}
19:25:30.029  WARN whats-up-docker: Anonymous authentication is enabled; please make sure that the app is not exposed to unsecure networks
19:25:30.041  INFO whats-up-docker/api: API/UI exposed on port 3000
19:25:31.015  INFO whats-up-docker/watcher.docker.local: Cron started (0 1 * * *)
19:25:31.058  WARN whats-up-docker: local_portainer - No Registry Provider found
19:25:31.064  INFO whats-up-docker/trigger.mqtt.mosquitto: Remove hass device [id=wud_container_local_wud]
19:25:31.076  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_portainer)
19:25:31.078  WARN whats-up-docker/watcher.docker.local: Error when processing some containers (Cannot read properties of undefined (reading 'tag'))
19:25:31.079  INFO whats-up-docker/watcher.docker.local: Cron finished (0 containers watched, 0 errors, 0 available updates)
19:25:31.891  INFO whats-up-docker/trigger.mqtt.mosquitto: Add hass device [id=wud_container_local_wud]
```

Thanks.

**Comment by fmartinou** [comment]
Hi,

```
19:25:28.912 WARN whats-up-docker/registry: Some triggers failed to register (Error when registering component dockercompose ("back" is not allowed)) 
```
My bad; the documentation is wrong;  the valid option is `WUD_TRIGGER_DOCKERCOMPOSE_WUD_BACKUP=true`

Can you retry with, please ?

(I just fixed the documentation)

**Comment by Ikes72000** [comment]
Hi,

Thanks for reply.
Trigger is created, but update doesn't work.
![image](https://user-images.githubusercontent.com/12248505/146565177-82a7fa60-b5ab-4b1b-90fd-c952d8347b7d.png)

![image](https://user-images.githubusercontent.com/12248505/146565343-1ef586de-a1c5-476a-bc05-a06f5e4ebc7c.png)

Log:
`
15:48:34.555  INFO whats-up-docker/trigger.mqtt.mosquitto: Register trigger with configuration {"url":"tcp://192.168.100.31:1883","mode":"batch","hass":{"prefix":"homeassistant","enabled":true},"topic":"wud/container","threshold":"all","once":true,"simpletitle":"New ${kind} found for container ${name}","simplebody":"Container ${name} running with ${kind} ${local} can be updated to ${kind} ${remote}\n${link}","batchtitle":"${count} updates available"}
15:48:34.718  INFO whats-up-docker/registry: Register all components of kind trigger for provider dockercompose
15:48:34.743  INFO whats-up-docker/trigger.dockercompose.wud: Register trigger with configuration {"file":"/home/ikes/wud/docker-compose.yml","prune":true,"backup":true,"threshold":"all","mode":"single","once":true,"simpletitle":"New ${kind} found for container ${name}","simplebody":"Container ${name} running with ${kind} ${local} can be updated to ${kind} ${remote}\n${link}","batchtitle":"${count} updates available"}
15:48:34.765  INFO whats-up-docker/registry: No Registry configured => Init a default one (Docker Hub with default options)
15:48:35.158  INFO whats-up-docker/registry.hub: Register registry with configuration {}
15:48:36.913  INFO whats-up-docker/watcher.docker.local: Register watcher with configuration {"cron":"0 1 * * *","watchall":false,"socket":"/var/run/docker.sock","port":2375,"watchbydefault":true}
15:48:36.924  INFO whats-up-docker/watcher.docker.local: Cron scheduled (0 1 * * *)
15:48:36.957  INFO whats-up-docker/registry: No authentication configured => Allow anonymous access
15:48:36.963  INFO whats-up-docker/authentication.anonymous.anonymous: Register authentication with configuration {}
15:48:36.995  WARN whats-up-docker: Anonymous authentication is enabled; please make sure that the app is not exposed to unsecure networks
15:48:37.027  INFO whats-up-docker/api: API/UI exposed on port 3000
15:48:37.944  INFO whats-up-docker/watcher.docker.local: Cron started (0 1 * * *)
15:48:37.972  WARN whats-up-docker: local_portainer - No Registry Provider found
15:48:37.984  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_portainer)
15:48:37.987  WARN whats-up-docker/watcher.docker.local: Error when processing some containers (Cannot read properties of undefined (reading 'tag'))
15:48:37.987  INFO whats-up-docker/watcher.docker.local: Cron finished (0 containers watched, 0 errors, 0 available updates)`

Thanks

**Comment by fmartinou** [comment]
Hi,

My guess is that you fixed the configuration **after** the update event had been recorded.

Could you retry with an empty state?
_(I mean: removing all files from the `/store` folder and restarting the wud container)._

By the way, I can also see in your logs that you have another container that wud cannot track (`portainer`).
Obviously, WUD is considering that is doesn't come from the Hub registry.
If so, you could configure it to be ignored or configure the support for other registries in WUD.

**Comment by Ikes72000** [comment]
I have this in log after restarting wud container
`
18:12:40.004  WARN whats-up-docker/trigger.dockercompose.wud: Error (Cannot read properties of undefined (reading 'error'))`

Does the update of container begin immediately?

**Comment by fmartinou** [comment]
> Does the update of container begin immediately?

Yes it does (the watcher is triggered few seconds after the service has been started).

Could you run WUD with `WUD_LOG_LEVEL=debug` to get the most possible info?

_PS: Honestly, I've never tried to use the Docker-Compose trigger to auto-update WUD itself.
Maybe some stuff is not working as expected for this use-case... 🤔 ._

**Comment by Ikes72000** [comment]
Log in debug mode:
`18:44:10.391  INFO whats-up-docker: What's up Docker? is starting (version = 5.11.1),
18:44:10.392  INFO whats-up-docker/store: Load store from (/store/wud.json),
18:44:10.407  INFO whats-up-docker/store: Create Collection app,
18:44:10.409  INFO whats-up-docker/store: Migrate data from version undefined to version 5.11.1,
18:44:10.410  INFO whats-up-docker/store: Create Collection containers,
18:44:10.410  INFO whats-up-docker/prometheus: Init Prometheus module,
18:44:10.418 DEBUG whats-up-docker: Start container metrics interval,
18:44:10.420  INFO whats-up-docker/registry: Register all components of kind trigger for provider mqtt,
18:44:10.526  INFO whats-up-docker/trigger.mqtt.mosquitto: Register trigger with configuration {"url":"tcp://192.168.100.31:1883","mode":"batch","hass":{"prefix":"homeassistant","enabled":true},"topic":"wud/container","threshold":"all","once":true,"simpletitle":"New ${kind} found for container ${name}","simplebody":"Container ${name} running with ${kind} ${local} can be updated to ${kind} ${remote}\n${link}","batchtitle":"${count} updates available"},
18:44:10.618  INFO whats-up-docker/registry: Register all components of kind trigger for provider dockercompose,
18:44:10.656  INFO whats-up-docker/trigger.dockercompose.wud: Register trigger with configuration {"file":"/home/ikes/wud/docker-compose.yml","prune":true,"backup":true,"threshold":"all","mode":"single","once":true,"simpletitle":"New ${kind} found for container ${name}","simplebody":"Container ${name} running with ${kind} ${local} can be updated to ${kind} ${remote}\n${link}","batchtitle":"${count} updates available"},
18:44:10.656 DEBUG whats-up-docker/trigger.dockercompose.wud: Configure "batch" mode,
18:44:10.687 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Configure "single" mode,
18:44:10.688  INFO whats-up-docker/registry: No Registry configured => Init a default one (Docker Hub with default options),
18:44:10.974  INFO whats-up-docker/registry.hub: Register registry with configuration {},
18:44:11.901  INFO whats-up-docker/watcher.docker.local: Register watcher with configuration {"cron":"0 1 * * *","watchall":false,"socket":"/var/run/docker.sock","port":2375,"watchbydefault":true},
18:44:11.903  INFO whats-up-docker/watcher.docker.local: Cron scheduled (0 1 * * *),
18:44:11.914  INFO whats-up-docker/registry: No authentication configured => Allow anonymous access,
18:44:11.918  INFO whats-up-docker/authentication.anonymous.anonymous: Register authentication with configuration {},
18:44:11.919 DEBUG whats-up-docker/api: API/UI enabled => Start Http listener on port 3000,
18:44:11.929  WARN whats-up-docker: Anonymous authentication is enabled; please make sure that the app is not exposed to unsecure networks,
18:44:11.940  INFO whats-up-docker/api: API/UI exposed on port 3000,
18:44:12.914  INFO whats-up-docker/watcher.docker.local: Cron started (0 1 * * *),
18:44:12.981  WARN whats-up-docker: local_portainer - No Registry Provider found,
18:44:12.994 DEBUG whats-up-docker/watcher.docker.local: Start watching (container=local_wud),
18:44:12.995 DEBUG whats-up-docker/registry.hub: hub - Get fmartinou/whats-up-docker tags,
18:44:13.005 DEBUG whats-up-docker/watcher.docker.local: Start watching (container=local_zigbee2mqtt),
18:44:13.005 DEBUG whats-up-docker/registry.hub: hub - Get koenkk/zigbee2mqtt tags,
18:44:13.006 DEBUG whats-up-docker/watcher.docker.local: Start watching (container=local_nodered),
18:44:13.006 DEBUG whats-up-docker/registry.hub: hub - Get nodered/node-red tags,
18:44:13.007 DEBUG whats-up-docker/watcher.docker.local: Start watching (container=local_mosquitto),
18:44:13.007 DEBUG whats-up-docker/registry.hub: hub - Get library/eclipse-mosquitto tags,
18:44:13.008 DEBUG whats-up-docker/watcher.docker.local: Start watching (container=local_portainer),
18:44:13.009  WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_portainer),
18:44:13.009 DEBUG whats-up-docker/watcher.docker.local: Unsupported Registry unknown (container=local_portainer),
    Error: Unsupported Registry unknown,
        at getRegistry (/home/node/app/watchers/providers/docker/Docker.js:100:15),
        at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:399:34),
        at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:321:53),
        at /home/node/app/watchers/providers/docker/Docker.js:295:52,
        at Array.map (<anonymous>),
        at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:295:28),
        at processTicksAndRejections (node:internal/process/task_queues:96:5),
        at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:262:34),
18:44:13.010 DEBUG whats-up-docker/watcher.docker.local: Container watched for the first time (container=local_portainer),
18:44:13.012  INFO whats-up-docker/trigger.mqtt.mosquitto: Add hass device [id=wud_container_local_portainer],
18:44:13.014 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Publish container result to wud/container/local/portainer,
18:44:13.860 DEBUG whats-up-docker/watcher.docker.local: Container watched for the first time (container=local_wud),
18:44:13.862  INFO whats-up-docker/trigger.mqtt.mosquitto: Add hass device [id=wud_container_local_wud],
18:44:13.863 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Run trigger (container=local_wud),
18:44:13.863 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Publish container result to wud/container/local/wud,
18:44:13.864 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Publish container result to wud/container/local/wud,
18:44:13.871 DEBUG whats-up-docker/watcher.docker.local: Container watched for the first time (container=local_mosquitto),
18:44:13.872  INFO whats-up-docker/trigger.mqtt.mosquitto: Add hass device [id=wud_container_local_mosquitto],
18:44:13.873 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Publish container result to wud/container/local/mosquitto,
18:44:13.923 DEBUG whats-up-docker/watcher.docker.local: Container watched for the first time (container=local_zigbee2mqtt),
18:44:13.924  INFO whats-up-docker/trigger.mqtt.mosquitto: Add hass device [id=wud_container_local_zigbee2mqtt],
18:44:13.925 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Publish container result to wud/container/local/zigbee2mqtt,
18:44:14.780 DEBUG whats-up-docker/watcher.docker.local: Container watched for the first time (container=local_nodered),
18:44:14.781  INFO whats-up-docker/trigger.mqtt.mosquitto: Add hass device [id=wud_container_local_nodered],
18:44:14.782 DEBUG whats-up-docker/trigger.mqtt.mosquitto: Publish container result to wud/container/local/nodered,
18:44:14.783 DEBUG whats-up-docker/trigger.dockercompose.wud: Run trigger batch,
18:44:14.784  INFO whats-up-docker/watcher.docker.local: Cron finished (5 containers watched, 1 errors, 1 available updates),
18:44:14.785  WARN whats-up-docker/trigger.dockercompose.wud: Error (Cannot read properties of undefined (reading 'error')),
18:44:14.786 DEBUG whats-up-docker/trigger.dockercompose.wud: Cannot read properties of undefined (reading 'error'),
    TypeError: Cannot read properties of undefined (reading 'error'),
        at getComposeFile (/home/node/app/triggers/providers/dockercompose/Dockercompose.js:15:18),
        at async Dockercompose.triggerBatch (/home/node/app/triggers/providers/dockercompose/Dockercompose.js:57:25),
        at async Dockercompose.handleContainerReports (/home/node/app/triggers/providers/Trigger.js:75:17)`

**Comment by Ikes72000** [comment]
I tried with another container, but same problem, there is no update.

![image](https://user-images.githubusercontent.com/12248505/146611513-26582d8b-539e-436b-8fdc-291d3f2af071.png)

`version: '3'

services:
  whatsupdocker:
    image: fmartinou/whats-up-docker:5.11.1
    container_name: wud
    hostname: wud
    domainname: automation.home
    networks:
      - supervision
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data:/store
      - ${PWD}/docker-compose.yml:/wud/docker-compose.yml
      - ${PWD}/docker-compose.yml:/mosquitto/docker-compose.yml
    environment:
      - TZ=Europe/Paris
      - WUD_LOG_LEVEL=debug
      - WUD_WATCHER_LOCAL_CRON=0 1 * * *
      - WUD_WATCHER_LOCAL_WATCHALL=false
      - WUD_TRIGGER_MQTT_MOSQUITTO_MODE=batch
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=tcp://192.168.100.31:1883
      #- WUD_TRIGGER_MQTT_MOSQUITTO_USER=XXXXXXXXXXXXX
      #- WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=XXXXXXXXXX
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_PREFIX=homeassistant
      - WUD_TRIGGER_DOCKERCOMPOSE_WUD_FILE=${PWD}/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_WUD_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_WUD_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_MOSQUITTO_FILE=/home/ikes/mosquitto/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_MOSQUITTO_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_MOSQUITTO_PRUNE=true
    labels:
      - wud.watch=true
      - wud.watch.digest=false
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}
    restart: unless-stopped

networks:
  supervision:
    external: true
`

**Comment by fmartinou** [comment]
Hi,

I may have a clue:

You bind mount your docker-compose file as
- `${PWD}/docker-compose.yml:/wud/docker-compose.yml`

And you configure WUD to get it at `WUD_TRIGGER_DOCKERCOMPOSE_WUD_FILE=${PWD}/docker-compose.yml` which is not correct.

The correct value should be
 `WUD_TRIGGER_DOCKERCOMPOSE_WUD_FILE=/wud/docker-compose.yml`

(Don't forget that wud configuration is related to files located **in the wud container, not on the host machine**.)


If I'm right, though I must check why the root error is not clearly logged 🤔 .

One other thing; 
Why are you configuring the docker-compose trigger twice (both handling the same docker-compose file) (`WUD_TRIGGER_DOCKERCOMPOSE_WUD` and `WUD_TRIGGER_DOCKERCOMPOSE_MOSQUITTO`)?

**Comment by Ikes72000** [comment]
Hi,

It's not really clear, for me, on how to 
It's not really clear for me, on how to configure  docker-compose trigger.
On my server, applications and compose files are organized like this:
![image](https://user-images.githubusercontent.com/12248505/146638832-b35e0ab9-152e-490e-a480-a844237164ce.png)

If I want to configure the trigger on most of my containers, what should I do?

Thanks.

**Comment by fmartinou** [comment]
IMHO, the first you need to do is to merge all your compose files in a big one instead of managing 1 compose file per service.(this is the main purpose of Docker-Compose)

Even if your situation should work, it's not common and makes configuration much complicated.

You could change for something like that:
```
docker-compose.yml # containing the configuration for all your local services (mosquitto, nodered, wud, z2m)
mosquitto/
  config/
  data/
  log/
nodered/
  data/
wud/
  data/
z2m/
  data/
```

Then, you can configure WUD to automatically update & apply the updated on your compose file:
```yaml
version: '3'

services:
  whatsupdocker:
  image: fmartinou/whats-up-docker:5.11.1
  container_name: wud
  ports:
    - 3000:3000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${PWD}/wud/data:/store
    - ${PWD}/docker-compose.yml:/wud/docker-compose.yml
  environment:
    - TZ=Europe/Paris
    - WUD_WATCHER_LOCAL_CRON=0 1 * * *
    - WUD_WATCHER_LOCAL_WATCHALL=false
    - WUD_TRIGGER_DOCKERCOMPOSE_WUD_FILE=/wud/docker-compose.yml
    - WUD_TRIGGER_DOCKERCOMPOSE_WUD_BACKUP=true
    - WUD_TRIGGER_DOCKERCOMPOSE_WUD_PRUNE=true
  labels:
    - wud.watch=true
    - wud.tag.include=^\d+.\d+.\d+$$
    - wud.link.template=https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}
```

**Comment by fmartinou** [comment]
Any news?

Are you still stuck or did you find a way out?

**Comment by fmartinou** [comment]
I close this issue because of inactivity; feel free to reopen if it's still relevant.

**Comment by zimmra** [comment]
@fmartinou 
Could use a little direction on this
I've got several compose files, not one for each service but general categories (e.g. downloads has sabnzbd, sonarr, radar, etc, whereas devops compose file has VS code, gitea, bookstack, etc and so on for each category)

I partition/segment my compose files so that if I for instance wanted to take my home compose file and move it to a different host, I don't affect every container. 

With the below trigger, I expected it to just update the containers/images in my `/mnt/compose/downloads/docker-compose.yml` file, but it updated everything even outside of this compose file. 

Is there a way to accomplish what I am trying to do with segmented compose files?

```yaml
    environment:
      - TZ=America/Los_Angeles
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://redacted:redacted@mqtt:1883
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_DOCKERCOMPOSE_downloadsupdate_FILE=/mnt/compose/downloads/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_downloadsupdate_PRUNE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/docker/configs/portainer/compose/12:/mnt/compose/downloads
      - /media/docker/configs/portainer/compose/6:/mnt/compose/database
      - /media/docker/configs/portainer/compose/31:/mnt/compose/devops
      - /media/docker/configs/portainer/compose/25:/mnt/compose/home
      - /media/docker/configs/portainer/compose/26:/mnt/compose/media
      - /media/docker/configs/portainer/compose/20:/mnt/compose/network
```

**Comment by fmartinou** [comment]
Hi,

I understand you want `wud` to automatically update all the containers from `/mnt/compose/downloads/docker-compose.yml`.
But what about the containers from the other compose files;
- do you want them to be totally ignored by `wud`?
- do you want them to be tracked by `wud` but without automatically updating them?
- why are you mounting the other compose files to `wud` if you don't want it to update them ?

I'll do some tests with a config similar to yours to see what exactly happens.

In the meantime, you can still [add labels on your containers](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels) to decide whether `wud` must track them or not (`wud.watch=true | false`).

**Comment by zimmra** [comment]
> * do you want them to be totally ignored by `wud`?

Yes and no, I want to set discrete triggers that behave differently per each compose file, so that if it is not defined in a trigger then yes it is ignored



> * do you want them to be tracked by `wud` but without automatically updating them?

For me personally, yes I will be tracking them all regardless of the compose file they're in, triggering would be different



> * why are you mounting the other compose files to `wud` if you don't want it to update them ?

"Internally" I classify my containers into 3 categories Critical > Important > Normal

All containers I at least want to know when an updated image is available

Normal containers I don't care if they get updated in real-time automatically - I don't have much to lose if something breaks.

Important containers I also don't mind automatic updates, but would like to have control over the timing. 
For instance, my `home` compose file - I don't want these to update in real-time automatically, I ideally I would want them to wait until X number weeks after the latest image dropped before automatically upgrading it. 
The option to manually trigger this upgrade in the event I know have time to troubleshoot a breaking change would be beneficial too

Critical containers, I never want to update automatically. I would just like to be notified, and then have the option to manually trigger the update. 

> In the meantime, you can still [add labels on your containers](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=labels) to decide whether `wud` must track them or not (`wud.watch=true | false`).

I don't have any containers I don't want watched though - I am just wanting to manipulate how the watched containers are triggered as I think a blanket 

Perhaps I am using WUD 'wrong', but I don't see much of a usecase for myself in triggering automatic updates if when something is watched then it must be part of the upgrade trigger

**Comment by zimmra** [comment]
My current workflow for updating containers is I have a script that performs the same function as `..._DRYRUN`

Some of my compose stacks I just go ahead and blindly update (in Portainer)

Other compose stacks I review the updates and apply with discretion. Usually I apply the updated images at this time, because I already know that I have time to troubleshoot.
Some of these containers, if affected by a breaking change, would cause lots of problems for me. 

Really what I'm looking is a way to automate what I can define as being automatable (and have some control over the automation instead of a blanket system-wide approach), and monitor what I define as monitor-only

**Comment by t-pohl** [comment]
@fmartinou Any update concerning the request of @zimmra ? The workflow described in the [comment above](https://github.com/fmartinou/whats-up-docker/issues/90#issuecomment-1138842911) is exactly what I'm looking for and enables a more granular approach on how to deal with different container "categories". For my setup it is not feasiable to merge every deployed container into a single compose (they belong to different microservices which are in different repos).
