### ISSUE TITLE
Registry docker-compose correction

### ISSUE THREAD

**Issue by camps7ee** [fmartinou/whats-up-docker#91]
Not really an issue but I'd thought I'd correct part of the REGISTRY section in the documentation for docker-compose

`environment:
     - WUD_REGISTRY_<REGISTRY>=`

If you don't add the `=` it won't pick up the variable and default to Docker Hub as it's registry.

Thanks for a very interesting piece of service :)

**Comment by fmartinou** [comment]
Thanks for your improvement request; the documentation has been fixed!
