### ISSUE TITLE
Issue since last update, restarting containers triggering 'Refresh All'

### ISSUE THREAD

**Issue by oliroe** [fmartinou/whats-up-docker#94]
Hi

Since I updated to the latest version WUD seems to trigger a refresh all whenever a container restarts. 

![image](https://user-images.githubusercontent.com/4500141/147418854-f948020c-bd96-48ed-a1a2-dfa0b2e67b68.png)

**Comment by fmartinou** [comment]
Hi,

In the latest version, WUD is listening to Docker events to sync state as soon as possible.
In case of `create` or `destroy` events, a `refresh all` is triggered.

Maybe are you in a situation where containers are created/destroyed all over the time?
If so, you can disable the `docker events feature` on your watcher by setting `WUD_WATCHER_{watcher_name}_WATCHEVENTS=false`?

**Comment by oliroe** [comment]
Hi
I use Portainer and Recreate to update my containers, I think the command stops the container, downloads the latest image and recreates it with that image. Every time I update a container I get the refresh all notification so it sounds like I need to disable the feature as you say.
Thanks again
