### ISSUE TITLE
Unknown registry for lscr.io image

### ISSUE THREAD

**Issue by lcavalli** [fmartinou/whats-up-docker#96]
In running a wireguard docker container pulled from lscr.io, but wud doesn't recognize the container.
The error log:

```
15:32:30.288  WARN whats-up-docker: local_wud - No Registry Provider found
15:32:30.296  WARN whats-up-docker/watcher.docker.local: Error when trying to get the list of the containers to watch (Error when validating container properties ValidationError: "image.registry.url" is required)
15:32:30.297  INFO whats-up-docker/watcher.docker.local: Cron finished (0 containers watched, 0 errors, 0 available updates)
15:33:26.797  WARN whats-up-docker: local_wud - No Registry Provider found
15:33:26.803  WARN whats-up-docker/watcher.docker.local: Error when trying to get the list of the containers to watch (Error when validating container properties ValidationError: "image.registry.url" is required)
15:33:27.861  WARN whats-up-docker: local_wud - No Registry Provider found
15:33:27.863  WARN whats-up-docker/watcher.docker.local: Error when trying to get the list of the containers to watch (Error when validating container properties ValidationError: "image.registry.url" is required)
15:33:34.585  WARN whats-up-docker: local_wud - No Registry Provider found
15:33:34.587  WARN whats-up-docker/watcher.docker.local: Error when trying to get the list of the containers to watch (Error when validating container properties ValidationError: "image.registry.url" is required)
```

I'm running the container from docker and added also the following label:

```
--label image.registry.url=lscr.io/linuxserver/wireguard
```

![image](https://user-images.githubusercontent.com/6123641/149625876-19a43fb6-d119-4048-9025-4cbac7bb93bc.png)

Home Assistant from GitHub registry presents the same problem.

**Comment by lcavalli** [comment]
Adding -e WUD_REGISTRY_HUB= to the command line of docker wud run fixed the problem fir both Wireguard and Home Assistant containers.
Sorry.

**Comment by fmartinou** [comment]
I'm glad to see you figure it out by yourself 👍 

Actually, the Docker Hub registry is automatically enabled only when there is no registries configured at all (mainly to make new user onboarding easier).
If you enable at least 1 registry (LSCR for example), the Docker Hub registry isn't automatically enable anymore and you have to explicitly declare which registries you want to enable (including Docker Hub).
