### ISSUE TITLE
docker private registry

### ISSUE THREAD

**Issue by chichocom** [fmartinou/whats-up-docker#98]
Is it possible to add a private docker registry?

Thanks a lot

**Comment by fmartinou** [comment]
Hi,

What do you exactly mean with `private docker registry`?

A self-hosted docker registry?
If so, it's not supported by now but it's a perfectly valid request; I add the item to my todo list.

**Comment by chichocom** [comment]
Yes, a self-hosted docker registry. 
Thanks a lot.

**Comment by dapuzz** [comment]
Just to be sure I have understood well... is ghcr.io/home-assistant/home-assistant:stable a private registru?

**Comment by fmartinou** [comment]
Hi,

The GitHub registry can host public images as private images as well (ie authentication needed to pull them).

Concerning ghcr.io/home-assistant/home-assistant, these images can be publicly pulled.

GHCR is already supported by wud (both public and private images).

This issue is more related to self hosted Docker registries.

**Comment by simonhauck** [comment]
I think this project looks really promising! 
But since most of my images are cached by a private registry (to don't exceed my pull limit) I can't get any update information's. So I would love this feature as well!

**Comment by fmartinou** [comment]
Hi @simonhauck ,

Thanks for your support 👍 .
This feature request wasn't forgotten.
I cannot make any promise for a release date yet but I'll add it to the product, for sure :)
(external contributions are also welcome, btw)

**Comment by fmartinou** [comment]
> But since most of my images are cached by a private registry (to don't exceed my pull limit) I can't get any update information's.

Temporary alternative; why not hosting your images on the Github registry?
(It's free, you can keep your images private and there is not pull rate limit as for now.)

**Comment by fmartinou** [comment]
Hi,

It's implemented in `5.16.0`.
See the [related documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/custom/).

Thank you for your feedback!
