### ISSUE TITLE
Images from Docker Hub seem to always fail when using anonymous authentication

### ISSUE THREAD

**Issue by david-holbrook** [fmartinou/whats-up-docker#99]
When using public images from Docker Hub in my docker-compose.yml such as:

version: "3.9"
services:
  radarr:
    image: linuxserver/radarr
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/movies:/movies
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Australia/Hobart
      - UMASK=022
    ports:
      - 7878:7878
    restart: unless-stopped

I am finding that the docker-compose trigger is failing to pull new images when they are detected. I have also tried specifying the :latest tag with no change. It's a little out of my depth but although the hash seems correct, the pull command  will fail even if I try to run it manually.

Debug Log:

11:17:38.460  INFO whats-up-docker/trigger.dockercompose.docker-compose: Pull image linuxserver/radarr:sha256:ffae94ba60fda72230b505a7ae7e9fc794705392391e60a7475202ead8591197 (container=local_docker_radarr_1)
11:17:42.724  WARN whats-up-docker/trigger.dockercompose.docker-compose: Error when pulling image linuxserver/radarr:sha256:ffae94ba60fda72230b505a7ae7e9fc794705392391e60a7475202ead8591197 ((HTTP code 404) unexpected - manifest for linuxserver/radarr:ffae94ba60fda72230b505a7ae7e9fc794705392391e60a7475202ead8591197 not found: manifest unknown: manifest unknown ) (container=local_docker_radarr_1)
11:17:42.724  WARN whats-up-docker/trigger.dockercompose.docker-compose: Error ((HTTP code 404) unexpected - manifest for linuxserver/radarr:ffae94ba60fda72230b505a7ae7e9fc794705392391e60a7475202ead8591197 not found: manifest unknown: manifest unknown )
11:17:42.725 DEBUG whats-up-docker/trigger.dockercompose.docker-compose: (HTTP code 404) unexpected - manifest for linuxserver/radarr:ffae94ba60fda72230b505a7ae7e9fc794705392391e60a7475202ead8591197 not found: manifest unknown: manifest unknown 
Error: (HTTP code 404) unexpected - manifest for linuxserver/radarr:ffae94ba60fda72230b505a7ae7e9fc794705392391e60a7475202ead8591197 not found: manifest unknown: manifest unknown 
at /home/node/app/node_modules/docker-modem/lib/modem.js:324:17
at IncomingMessage.<anonymous> (/home/node/app/node_modules/docker-modem/lib/modem.js:351:9)
at IncomingMessage.emit (node:events:402:35)
at endReadableNT (node:internal/streams/readable:1343:12)
at processTicksAndRejections (node:internal/process/task_queues:83:21)

My WUD Compose:

  whatsupdocker:
    image: fmartinou/whats-up-docker
    volumes:
      - /volume1/docker/wud/config:/store
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/docker-compose.yml:/wud/docker-compose.yml
    environment:
      - TZ=Australia/Hobart
      - WUD_TRIGGER_HTTP_HOME-ASSISTANT_URL=http://example.com/api/webhook/wud
      - WUD_TRIGGER_DOCKERCOMPOSE_DOCKER-COMPOSE_FILE=/wud/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_DOCKER-COMPOSE_BACKUP=true
      - WUD_REGISTRY_HUB=
      - WUD_LOG_LEVEL=debug
    labels:
      - traefik.enable=false
    ports:
      - 3000:3000
    restart: unless-stopped

**Comment by dapuzz** [comment]
I am experiencing the same issue. Is this really related to anonymous authentication? Is there some workaround?

Thank you

**Comment by fmartinou** [comment]
Hi,

I think I managed to fix the issue; it will be part of the next `wud` release.
In the mean time, you can give it a try by testing the version `fmartinou/whats-up-docker:fix__99`

**Comment by dapuzz** [comment]
Wow! I found my container updated automagically! Thanks a lot, confirm it works with also with latest.

**Comment by fmartinou** [comment]
Thank you for the feedback!
I'm glad to know that it solves the issue!

**Comment by fmartinou** [comment]
Available in version `5.14.1`.
